// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025-2026 Christian Riesch, christian@riesch.at
//
// dsp-core/src/lib.rs — pure-math DSP primitives.
//
// No HAL dependencies — compiles for both the firmware target (thumbv7em) and
// the host (x86_64) so that unit tests can run with plain `cargo test -p dsp-core`.

// In normal (firmware) builds this crate is no_std.
// In test builds (cargo test -p dsp-core) std is available so that f32/f64
// math methods and Vec work without a separate libm dependency.
#![cfg_attr(not(test), no_std)]

// ---------------------------------------------------------------------------
// Pipeline constants
// ---------------------------------------------------------------------------

/// ADC / HRTIM sampling rate (200 kHz).  One DMA half-buffer = FRAME_SAMPLES.
pub const FRAME_SAMPLES: usize = 100;

/// Decimation / interpolation factor.
pub const FIR_DECIMATE_FACTOR: usize = 10;

/// Number of taps in the prototype lowpass FIR (shared by decimator and interpolator).
pub const FIR_NUM_TAPS: usize = 60;

/// Taps per polyphase sub-filter: FIR_NUM_TAPS / FIR_DECIMATE_FACTOR.
pub const FIR_SUBFILTER_TAPS: usize = FIR_NUM_TAPS / FIR_DECIMATE_FACTOR; // 6

/// Output samples per half-buffer after 10:1 decimation (DSP rate = 20 kHz).
pub const DECIMATED_LEN: usize = FRAME_SAMPLES / FIR_DECIMATE_FACTOR; // 10

// ---------------------------------------------------------------------------
// FIR prototype lowpass coefficients
// Generated by tools/design_decimate_filter.ipynb — do not edit manually.
// Cutoff 5 kHz, 60-tap Hamming window, Q31.  Shared by decimator and
// interpolator.  Stopband attenuation reaches -40 dB at 10 kHz.
// ---------------------------------------------------------------------------

#[rustfmt::skip]
pub const FIR_COEFFS_Q31: [i32; FIR_NUM_TAPS] = [
      -1890794,
      -1971130,
      -2123936,
      -2324026,
      -2525779,
      -2663835,
      -2655228,
      -2402891,
      -1800394,
       -737704,
        892341,
       3187185,
       6227709,
      10071807,
      14748755,
      20254744,
      26549872,
      33556841,
      41161496,
      49215254,
      57539380,
      65930935,
      74170157,
      82028943,
      89280014,
      95706338,
     101110327,
     105322362,
     108208197,
     109674881,
     109674881,
     108208197,
     105322362,
     101110327,
      95706338,
      89280014,
      82028943,
      74170157,
      65930935,
      57539380,
      49215254,
      41161496,
      33556841,
      26549872,
      20254744,
      14748755,
      10071807,
       6227709,
       3187185,
        892341,
       -737704,
      -1800394,
      -2402891,
      -2655228,
      -2663835,
      -2525779,
      -2324026,
      -2123936,
      -1971130,
      -1890794,
];

// ---------------------------------------------------------------------------
// Audio IIR filter constants
// Generated by tools/design_audio_filters.ipynb — do not edit manually.
// ---------------------------------------------------------------------------

/// Number of biquad sections in the highpass filter.
pub const HIGHPASS_STAGES: usize = 2;

/// Highpass filter coefficients: [[b0, b1, b2, -a1, -a2]; 2].
/// Direct Form II Transposed, normalised by a0.
/// Cutoff 200 Hz, Chebyshev I order 4, 0.3 dB ripple, fs = 20 kHz.
#[rustfmt::skip]
pub const HIGHPASS_COEFFS: [[f32; 5]; HIGHPASS_STAGES] = [
    [8.8843882084e-01, -1.7768776417e+00, 8.8843882084e-01, 1.8572715521e+00, -8.6588841677e-01],
    [1.0000000000e+00, -2.0000000000e+00, 1.0000000000e+00, 1.9743645191e+00, -9.7780704498e-01],
];

/// Number of biquad sections in the lowpass filter.
pub const LOWPASS_STAGES: usize = 2;

/// Lowpass filter coefficients: [[b0, b1, b2, -a1, -a2]; 2].
/// Direct Form II Transposed, normalised by a0.
/// Cutoff 2800 Hz, Chebyshev I order 4, 0.3 dB ripple, fs = 20 kHz.
#[rustfmt::skip]
pub const LOWPASS_COEFFS: [[f32; 5]; LOWPASS_STAGES] = [
    [1.0223765858e-02, 2.0447531715e-02, 1.0223765858e-02, 1.1647846699e+00, -4.0787613392e-01],
    [1.0000000000e+00, 2.0000000000e+00, 1.0000000000e+00, 1.0389341116e+00, -7.3549830914e-01],
];

// ---------------------------------------------------------------------------
// Compressor constants — copied from C reference implementation.
// ---------------------------------------------------------------------------

/// Compression threshold (linear amplitude).  Gain reduction starts here.
pub const COMP_THRESHOLD:   f32 = 0.3;
/// Compression ratio (4:1 above threshold).
pub const COMP_RATIO:       f32 = 4.0;
/// Make-up gain applied after gain computation.
pub const COMP_MAKEUP_GAIN: f32 = 1.5;
/// Attack coefficient: 1 − exp(−1 / (20000 × 0.0002))
pub const COMP_ATTACK_COEFF:  f32 = 0.22119922_f32;
/// Release coefficient: 1 − exp(−1 / (20000 × 0.1))
pub const COMP_RELEASE_COEFF: f32 = 0.00049987503_f32;

// ---------------------------------------------------------------------------
// SSB analytic FIR filter constants
// Generated by tools/design_ssb_filter.ipynb — do not edit manually.
// ---------------------------------------------------------------------------

/// Total length of the SSB analytic FIR shift register.
pub const SSB_FILTER_TAPS: usize = 257;
/// Non-zero I-path taps (even-indexed entries of the full 257-tap filter).
pub const SSB_REAL_TAPS: usize = 129;
/// Non-zero Q-path taps (odd-indexed entries of the full 257-tap filter).
pub const SSB_IMAG_TAPS: usize = 128;

/// I-path compact coefficients: full_filter[0, 2, 4, …, 256].
#[rustfmt::skip]
pub const SSB_REAL_COEFFS: [f32; SSB_REAL_TAPS] = [
    -1.0015372709e-06,  2.2930228170e-06,  3.3461501516e-06,  5.2559112191e-06,
     7.7128152043e-06,  1.0480947822e-05,  1.3278330698e-05,  1.5694196918e-05,
     1.7181313524e-05,  1.7058382582e-05,  1.4531447960e-05,  8.7336657089e-06,
    -1.2160819551e-06, -1.6135949409e-05, -3.6687335523e-05, -6.3266161305e-05,
    -9.5884810435e-05, -1.3405329082e-04, -1.7667168868e-04, -2.2194175108e-04,
    -2.6730718673e-04, -3.0943291495e-04, -3.4423696343e-04, -3.6698704935e-04,
    -3.7246421562e-04, -3.5518512595e-04, -3.0968984356e-04, -2.3093081836e-04,
    -1.1463979172e-04,  4.2201892938e-05,  2.4092476815e-04,  4.8072510981e-04,
     7.5826630928e-04,  1.0673451470e-03,  1.3986598933e-03,  1.7397002084e-03,
     2.0747862291e-03,  2.3852747399e-03,  2.6499389205e-03,  2.8455299325e-03,
     2.9475032352e-03,  2.9309017118e-03,  2.7713598683e-03,  2.4461979046e-03,
     1.9355559489e-03,  1.2235176982e-03,  2.9917375650e-04, -8.4243499441e-04,
    -2.1995522548e-03, -3.7631618325e-03, -5.5167032406e-03, -7.4360873550e-03,
    -9.4900242984e-03, -1.1640660465e-02, -1.3844528235e-02, -1.6053767875e-02,
    -1.8217587844e-02, -2.0283894613e-02, -2.2201064974e-02, -2.3919727653e-02,
    -2.5394538417e-02, -2.6585834101e-02, -2.7461096644e-02, -2.7996178716e-02,
     4.7182378173e-01, -2.7996178716e-02, -2.7461096644e-02, -2.6585834101e-02,
    -2.5394538417e-02, -2.3919727653e-02, -2.2201064974e-02, -2.0283894613e-02,
    -1.8217587844e-02, -1.6053767875e-02, -1.3844528235e-02, -1.1640660465e-02,
    -9.4900242984e-03, -7.4360873550e-03, -5.5167032406e-03, -3.7631618325e-03,
    -2.1995522548e-03, -8.4243499441e-04,  2.9917375650e-04,  1.2235176982e-03,
     1.9355559489e-03,  2.4461979046e-03,  2.7713598683e-03,  2.9309017118e-03,
     2.9475032352e-03,  2.8455299325e-03,  2.6499389205e-03,  2.3852747399e-03,
     2.0747862291e-03,  1.7397002084e-03,  1.3986598933e-03,  1.0673451470e-03,
     7.5826630928e-04,  4.8072510981e-04,  2.4092476815e-04,  4.2201892938e-05,
    -1.1463979172e-04, -2.3093081836e-04, -3.0968984356e-04, -3.5518512595e-04,
    -3.7246421562e-04, -3.6698704935e-04, -3.4423696343e-04, -3.0943291495e-04,
    -2.6730718673e-04, -2.2194175108e-04, -1.7667168868e-04, -1.3405329082e-04,
    -9.5884810435e-05, -6.3266161305e-05, -3.6687335523e-05, -1.6135949409e-05,
    -1.2160819551e-06,  8.7336657089e-06,  1.4531447960e-05,  1.7058382582e-05,
     1.7181313524e-05,  1.5694196918e-05,  1.3278330698e-05,  1.0480947822e-05,
     7.7128152043e-06,  5.2559112191e-06,  3.3461501516e-06,  2.2930228170e-06,
    -1.0015372709e-06,
];

/// Q-path compact coefficients: full_filter[1, 3, 5, …, 255].
#[rustfmt::skip]
pub const SSB_IMAG_COEFFS: [f32; SSB_IMAG_TAPS] = [
    -3.3779708701e-06, -1.9478195554e-06, -1.9168621748e-06, -1.2431479490e-06,
     3.5058798176e-07,  3.1770571240e-06,  7.5202710832e-06,  1.3611955183e-05,
     2.1579917302e-05,  3.1393814425e-05,  4.2810101149e-05,  5.5321052059e-05,
     6.8112261943e-05,  8.0034253187e-05,  8.9595356258e-05,  9.4980954600e-05,
     9.4105933385e-05,  8.4704472101e-05,  6.4458290581e-05,  3.1157334888e-05,
    -1.7107584426e-05, -8.1721678725e-05, -1.6330594372e-04, -2.6148100733e-04,
    -3.7464901106e-04, -4.9979775213e-04, -6.3234107802e-04, -7.6608348172e-04,
    -8.9319678955e-04, -1.0043596849e-03, -1.0889746482e-03, -1.1355153983e-03,
    -1.1319892947e-03, -1.0665055597e-03, -9.2794105876e-04, -7.0667639375e-04,
    -3.9537489647e-04,  1.0225045116e-05,  5.1055062795e-04,  1.1014989577e-03,
     1.7738512252e-03,  2.5128242560e-03,  3.2977983356e-03,  4.1022370569e-03,
     4.8938053660e-03,  5.6346827187e-03,  6.2820408493e-03,  6.7886435427e-03,
     7.1034799330e-03,  7.1723107249e-03,  6.9379662164e-03,  6.3401162624e-03,
     5.3141033277e-03,  3.7881801836e-03,  1.6779416474e-03, -1.1242580367e-03,
    -4.7694551758e-03, -9.4918282703e-03, -1.5692636371e-02, -2.4136526510e-02,
    -3.6484256387e-02, -5.7102695107e-02, -1.0211124271e-01, -3.1696969271e-01,
     3.1696969271e-01,  1.0211124271e-01,  5.7102695107e-02,  3.6484256387e-02,
     2.4136526510e-02,  1.5692636371e-02,  9.4918282703e-03,  4.7694551758e-03,
     1.1242580367e-03, -1.6779416474e-03, -3.7881801836e-03, -5.3141033277e-03,
    -6.3401162624e-03, -6.9379662164e-03, -7.1723107249e-03, -7.1034799330e-03,
    -6.7886435427e-03, -6.2820408493e-03, -5.6346827187e-03, -4.8938053660e-03,
    -4.1022370569e-03, -3.2977983356e-03, -2.5128242560e-03, -1.7738512252e-03,
    -1.1014989577e-03, -5.1055062795e-04, -1.0225045116e-05,  3.9537489647e-04,
     7.0667639375e-04,  9.2794105876e-04,  1.0665055597e-03,  1.1319892947e-03,
     1.1355153983e-03,  1.0889746482e-03,  1.0043596849e-03,  8.9319678955e-04,
     7.6608348172e-04,  6.3234107802e-04,  4.9979775213e-04,  3.7464901106e-04,
     2.6148100733e-04,  1.6330594372e-04,  8.1721678725e-05,  1.7107584426e-05,
    -3.1157334888e-05, -6.4458290581e-05, -8.4704472101e-05, -9.4105933385e-05,
    -9.4980954600e-05, -8.9595356258e-05, -8.0034253187e-05, -6.8112261943e-05,
    -5.5321052059e-05, -4.2810101149e-05, -3.1393814425e-05, -2.1579917302e-05,
    -1.3611955183e-05, -7.5202710832e-06, -3.1770571240e-06, -3.5058798176e-07,
     1.2431479490e-06,  1.9168621748e-06,  1.9478195554e-06,  3.3779708701e-06,
];

// ---------------------------------------------------------------------------
// FIR decimation filter
// ---------------------------------------------------------------------------

/// Single-channel FIR decimation filter (200 kHz → 20 kHz, factor 10), Q31.
pub struct FirDecimate {
    state: [i32; FIR_NUM_TAPS - 1],
}

impl FirDecimate {
    pub const fn new() -> Self {
        Self { state: [0i32; FIR_NUM_TAPS - 1] }
    }

    /// Decimate `input` (FRAME_SAMPLES Q31 samples) to DECIMATED_LEN Q31 samples.
    pub fn process(&mut self, input: &[i32; FRAME_SAMPLES]) -> [i32; DECIMATED_LEN] {
        let mut buf = [0i32; FIR_NUM_TAPS - 1 + FRAME_SAMPLES];
        buf[..FIR_NUM_TAPS - 1].copy_from_slice(&self.state);
        buf[FIR_NUM_TAPS - 1..].copy_from_slice(input);

        let mut output = [0i32; DECIMATED_LEN];
        for k in 0..DECIMATED_LEN {
            let start = k * FIR_DECIMATE_FACTOR;
            let acc: i64 = FIR_COEFFS_Q31
                .iter()
                .zip(buf[start..start + FIR_NUM_TAPS].iter())
                .map(|(&c, &x)| c as i64 * x as i64)
                .sum();
            output[k] = (acc >> 31).clamp(i32::MIN as i64, i32::MAX as i64) as i32;
        }

        self.state.copy_from_slice(&buf[FRAME_SAMPLES..]);
        output
    }
}

// ---------------------------------------------------------------------------
// FIR interpolation filter (Q31)
// ---------------------------------------------------------------------------

/// Single-channel polyphase FIR interpolation filter (20 kHz → 200 kHz, factor 10), Q31.
pub struct FirInterpolate {
    state: [i32; FIR_SUBFILTER_TAPS - 1],
}

impl FirInterpolate {
    pub const fn new() -> Self {
        Self { state: [0i32; FIR_SUBFILTER_TAPS - 1] }
    }

    /// Interpolate `input` (DECIMATED_LEN Q31 samples) to FRAME_SAMPLES Q31 samples.
    pub fn process(
        &mut self,
        input:  &[i32; DECIMATED_LEN],
        output: &mut [i32; FRAME_SAMPLES],
    ) {
        let mut buf = [0i32; FIR_SUBFILTER_TAPS - 1 + DECIMATED_LEN];
        buf[..FIR_SUBFILTER_TAPS - 1].copy_from_slice(&self.state);
        buf[FIR_SUBFILTER_TAPS - 1..].copy_from_slice(input);

        for k in 0..DECIMATED_LEN {
            for p in 0..FIR_DECIMATE_FACTOR {
                let mut acc = 0i64;
                for n in 0..FIR_SUBFILTER_TAPS {
                    let c = FIR_COEFFS_Q31[FIR_NUM_TAPS - 1 - p - n * FIR_DECIMATE_FACTOR];
                    let x = buf[k + FIR_SUBFILTER_TAPS - 1 - n];
                    acc += c as i64 * x as i64;
                }
                let scaled = acc * FIR_DECIMATE_FACTOR as i64;
                output[k * FIR_DECIMATE_FACTOR + p] =
                    (scaled >> 31).clamp(i32::MIN as i64, i32::MAX as i64) as i32;
            }
        }

        self.state.copy_from_slice(&buf[DECIMATED_LEN..]);
    }
}

// ---------------------------------------------------------------------------
// IIR biquad filter — Direct Form II Transposed, f32
// ---------------------------------------------------------------------------

/// Cascaded biquad filter, N sections, f32.
///
/// Coefficients per section: `[b0, b1, b2, -a1, -a2]` (a-coefficients sign-negated).
pub struct BiquadState<const N: usize> {
    s: [[f32; 2]; N],
}

impl<const N: usize> BiquadState<N> {
    pub const fn new() -> Self {
        Self { s: [[0.0f32; 2]; N] }
    }

    /// Process `input` through all N sections into `output` (slice lengths must match).
    pub fn process(
        &mut self,
        coeffs: &[[f32; 5]; N],
        input:  &[f32],
        output: &mut [f32],
    ) {
        debug_assert_eq!(input.len(), output.len());
        for (i, &x) in input.iter().enumerate() {
            let mut y = x;
            for (s, c) in self.s.iter_mut().zip(coeffs.iter()) {
                let [b0, b1, b2, na1, na2] = *c;
                let xin = y;
                y     = b0 * xin + s[0];
                s[0]  = b1 * xin + na1 * y + s[1];
                s[1]  = b2 * xin + na2 * y;
            }
            output[i] = y;
        }
    }
}

// ---------------------------------------------------------------------------
// Voice compressor
// ---------------------------------------------------------------------------

/// Envelope-follower compressor with asymmetric attack/release, 4:1 ratio.
pub struct Compressor {
    envelope: f32,
    gain:     f32,
}

impl Compressor {
    pub const fn new() -> Self {
        Self { envelope: 0.0, gain: 1.0 }
    }

    /// Process `input` into `output` (slice lengths must match).
    pub fn process(&mut self, input: &[f32], output: &mut [f32]) {
        debug_assert_eq!(input.len(), output.len());
        for (out, &sample) in output.iter_mut().zip(input.iter()) {
            let abs_s = if sample < 0.0 { -sample } else { sample };

            if abs_s > self.envelope {
                self.envelope += COMP_ATTACK_COEFF  * (abs_s - self.envelope);
            } else {
                self.envelope += COMP_RELEASE_COEFF * (abs_s - self.envelope);
            }

            if self.envelope > COMP_THRESHOLD {
                let overshoot  = self.envelope / COMP_THRESHOLD;
                let compressed = 1.0 + (overshoot - 1.0) / COMP_RATIO;
                self.gain      = COMP_THRESHOLD * compressed / self.envelope;
            } else {
                self.gain = 1.0;
            }

            let s = sample * self.gain * COMP_MAKEUP_GAIN;
            *out = if s > 1.0 { 1.0 } else if s < -1.0 { -1.0 } else { s };
        }
    }
}

// ---------------------------------------------------------------------------
// SSB analytic FIR filter
// ---------------------------------------------------------------------------

/// Complex analytic FIR filter producing I and Q from a real audio signal.
///
/// Shares a single 257-sample shift register for both paths.
pub struct SsbFilter {
    state: [f32; SSB_FILTER_TAPS],
}

impl SsbFilter {
    pub const fn new() -> Self {
        Self { state: [0.0f32; SSB_FILTER_TAPS] }
    }

    /// Process `input` into `i_out` and `q_out` (all slice lengths must match).
    pub fn process(
        &mut self,
        input: &[f32],
        i_out: &mut [f32],
        q_out: &mut [f32],
    ) {
        debug_assert_eq!(input.len(), i_out.len());
        debug_assert_eq!(input.len(), q_out.len());
        for k in 0..input.len() {
            self.state.copy_within(0..SSB_FILTER_TAPS - 1, 1);
            self.state[0] = input[k];

            i_out[k] = SSB_REAL_COEFFS
                .iter()
                .zip(self.state.iter().step_by(2))
                .map(|(&c, &x)| c * x)
                .sum();

            q_out[k] = SSB_IMAG_COEFFS
                .iter()
                .zip(self.state[1..].iter().step_by(2))
                .map(|(&c, &x)| c * x)
                .sum();
        }
    }
}

// ---------------------------------------------------------------------------
// Sample format conversion helpers
// ---------------------------------------------------------------------------

/// Convert a 12-bit right-aligned ADC sample (0…4095) to Q31.
#[inline]
pub fn adc_to_q31(sample: u16) -> i32 {
    (sample as i32 - 2048) << 19
}

/// Convert a Q31 sample to normalised f32 in [−1.0, 1.0).
#[inline]
pub fn q31_to_f32(sample: i32) -> f32 {
    sample as f32 * (1.0 / 2_147_483_648.0_f32)
}

/// Convert a normalised f32 in [−1.0, 1.0] to Q31, saturating at limits.
#[inline]
pub fn f32_to_q31(sample: f32) -> i32 {
    let v = sample * 2_147_483_648.0_f32;
    if v >= i32::MAX as f32 { i32::MAX }
    else if v <= i32::MIN as f32 { i32::MIN }
    else { v as i32 }
}

// ---------------------------------------------------------------------------
// Unit tests — run on the host with: cargo test -p dsp-core
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // Compute RMS of a Q31 slice, returned as a normalised f32.
    fn rms_q31(samples: &[i32]) -> f32 {
        let sum_sq: f64 = samples.iter()
            .map(|&s| { let f = s as f64 / 2_147_483_648.0; f * f })
            .sum();
        (sum_sq / samples.len() as f64).sqrt() as f32
    }

    fn rms_f32(samples: &[f32]) -> f32 {
        let sum_sq: f32 = samples.iter().map(|&s| s * s).sum();
        (sum_sq / samples.len() as f32).sqrt()
    }

    // Generate N samples of a sine at `freq_hz` sampled at `fs_hz`.
    // Amplitude `amp` (normalised), returned as Q31.
    fn sine_q31(freq_hz: f64, fs_hz: f64, amp: f64, n: usize) -> Vec<i32> {
        use std::f64::consts::PI;
        (0..n).map(|i| {
            let s = amp * (2.0 * PI * freq_hz * i as f64 / fs_hz).sin();
            (s * i32::MAX as f64) as i32
        }).collect()
    }

    fn sine_f32(freq_hz: f64, fs_hz: f64, amp: f32, n: usize) -> Vec<f32> {
        use std::f64::consts::PI;
        (0..n).map(|i| {
            (amp as f64 * (2.0 * PI * freq_hz * i as f64 / fs_hz).sin()) as f32
        }).collect()
    }

    // ---------------------------------------------------------------------------
    // FIR decimator
    // ---------------------------------------------------------------------------

    #[test]
    fn test_fir_decimate_passband_1khz() {
        // A 1 kHz sine at 200 kHz should pass through with near-unity gain.
        // Run 10 frames (1000 input → 100 output samples); skip first frame for settling.
        let input = sine_q31(1_000.0, 200_000.0, 0.5, FRAME_SAMPLES * 10);
        let mut dec = FirDecimate::new();
        let mut output = Vec::new();
        for chunk in input.chunks_exact(FRAME_SAMPLES) {
            let arr: [i32; FRAME_SAMPLES] = chunk.try_into().unwrap();
            output.extend_from_slice(&dec.process(&arr));
        }
        // Discard first DECIMATED_LEN output samples (filter settling).
        let out_rms   = rms_q31(&output[DECIMATED_LEN..]);
        let in_rms    = rms_q31(&input[FRAME_SAMPLES..]);
        // Gain should be within ±3 dB of unity.
        assert!(out_rms > in_rms * 0.7, "passband 1 kHz too attenuated: in={in_rms:.4} out={out_rms:.4}");
        assert!(out_rms < in_rms * 1.4, "passband 1 kHz amplified: in={in_rms:.4} out={out_rms:.4}");
    }

    #[test]
    fn test_fir_decimate_stopband_12khz() {
        // A 12 kHz sine is above the -40 dB point (10 kHz) and must be strongly attenuated.
        let input = sine_q31(12_000.0, 200_000.0, 0.5, FRAME_SAMPLES * 20);
        let mut dec = FirDecimate::new();
        let mut output = Vec::new();
        for chunk in input.chunks_exact(FRAME_SAMPLES) {
            let arr: [i32; FRAME_SAMPLES] = chunk.try_into().unwrap();
            output.extend_from_slice(&dec.process(&arr));
        }
        let out_rms = rms_q31(&output[DECIMATED_LEN..]);
        let in_rms  = rms_q31(&input[FRAME_SAMPLES..]);
        // Expect at least -40 dB attenuation (amplitude ratio < 0.01).
        assert!(out_rms < in_rms * 0.01, "stopband 12 kHz not attenuated enough: in={in_rms:.4} out={out_rms:.6}");
    }

    // ---------------------------------------------------------------------------
    // IIR highpass biquad
    // ---------------------------------------------------------------------------

    #[test]
    fn test_highpass_rejects_dc() {
        // Feed DC = 1.0, check the output settles near zero.
        let input = vec![1.0f32; 2000];
        let mut hp = BiquadState::<HIGHPASS_STAGES>::new();
        let mut output = vec![0.0f32; 2000];
        hp.process(&HIGHPASS_COEFFS, &input, &mut output);
        // Tail of the output (after settling) must be near zero.
        let tail_rms = rms_f32(&output[1500..]);
        assert!(tail_rms < 1e-3, "HP filter passes DC: tail_rms={tail_rms:.6}");
    }

    #[test]
    fn test_highpass_passes_1khz() {
        // 1 kHz (well above 200 Hz cutoff) should pass with near-unity gain.
        let input = sine_f32(1_000.0, 20_000.0, 0.5, 2000);
        let mut hp = BiquadState::<HIGHPASS_STAGES>::new();
        let mut output = vec![0.0f32; 2000];
        hp.process(&HIGHPASS_COEFFS, &input, &mut output);
        let in_rms  = rms_f32(&input[500..]);
        let out_rms = rms_f32(&output[500..]);
        assert!(out_rms > in_rms * 0.7, "HP filter attenuates 1 kHz: in={in_rms:.4} out={out_rms:.4}");
    }

    // ---------------------------------------------------------------------------
    // IIR lowpass biquad
    // ---------------------------------------------------------------------------

    #[test]
    fn test_lowpass_passes_500hz() {
        let input = sine_f32(500.0, 20_000.0, 0.5, 2000);
        let mut lp = BiquadState::<LOWPASS_STAGES>::new();
        let mut output = vec![0.0f32; 2000];
        lp.process(&LOWPASS_COEFFS, &input, &mut output);
        let in_rms  = rms_f32(&input[500..]);
        let out_rms = rms_f32(&output[500..]);
        assert!(out_rms > in_rms * 0.7, "LP filter attenuates 500 Hz: in={in_rms:.4} out={out_rms:.4}");
    }

    #[test]
    fn test_lowpass_rejects_4khz() {
        // 4 kHz is well above the 2800 Hz cutoff.
        let input = sine_f32(4_000.0, 20_000.0, 0.5, 2000);
        let mut lp = BiquadState::<LOWPASS_STAGES>::new();
        let mut output = vec![0.0f32; 2000];
        lp.process(&LOWPASS_COEFFS, &input, &mut output);
        let in_rms  = rms_f32(&input[500..]);
        let out_rms = rms_f32(&output[500..]);
        // 4 kHz is 1.43× above the 2800 Hz cutoff; expect at least -14 dB attenuation.
        assert!(out_rms < in_rms * 0.2, "LP filter passes 4 kHz: in={in_rms:.4} out={out_rms:.4}");
    }

    // ---------------------------------------------------------------------------
    // Compressor
    // ---------------------------------------------------------------------------

    #[test]
    fn test_compressor_reduces_loud_signal() {
        // Feed a sustained 0.8-amplitude signal; after attack settling the
        // output should be quieter than the input.
        let input = vec![0.8f32; 2000];
        let mut comp = Compressor::new();
        let mut output = vec![0.0f32; 2000];
        comp.process(&input, &mut output);
        let in_rms  = rms_f32(&input[500..]);
        let out_rms = rms_f32(&output[500..]);
        assert!(out_rms < in_rms, "Compressor did not reduce level: in={in_rms:.4} out={out_rms:.4}");
    }

    #[test]
    fn test_compressor_does_not_clip() {
        let input = vec![0.95f32; 5000];
        let mut comp = Compressor::new();
        let mut output = vec![0.0f32; 5000];
        comp.process(&input, &mut output);
        for &s in &output {
            assert!(s >= -1.0 && s <= 1.0, "Compressor output out of range: {s}");
        }
    }

    #[test]
    fn test_compressor_passes_quiet_signal() {
        // Signal well below threshold: gain = 1, makeup applied, output ≈ input × makeup.
        let amp = 0.1f32; // below COMP_THRESHOLD = 0.3
        let input = vec![amp; 5000];
        let mut comp = Compressor::new();
        let mut output = vec![0.0f32; 5000];
        comp.process(&input, &mut output);
        // After settling, gain = 1.0 and output ≈ input * COMP_MAKEUP_GAIN.
        let expected = (amp * COMP_MAKEUP_GAIN).min(1.0);
        let tail_rms = rms_f32(&output[1000..]);
        assert!((tail_rms - expected).abs() < 0.01,
            "Quiet signal: expected≈{expected:.3} got≈{tail_rms:.3}");
    }

    // ---------------------------------------------------------------------------
    // FIR interpolator — round-trip test
    // ---------------------------------------------------------------------------

    #[test]
    fn test_fir_interpolate_round_trip_rms() {
        // Decimate then interpolate a 1 kHz sine.  The round-trip should
        // roughly preserve signal energy (within 3 dB).
        let input = sine_q31(1_000.0, 200_000.0, 0.5, FRAME_SAMPLES * 20);
        let mut dec = FirDecimate::new();
        let mut interp = FirInterpolate::new();
        let mut output = vec![0i32; FRAME_SAMPLES * 20];

        for (frame, chunk) in input.chunks_exact(FRAME_SAMPLES).enumerate() {
            let arr_in: [i32; FRAME_SAMPLES] = chunk.try_into().unwrap();
            let decimated = dec.process(&arr_in);
            let mut arr_out = [0i32; FRAME_SAMPLES];
            interp.process(&decimated, &mut arr_out);
            output[frame * FRAME_SAMPLES..(frame + 1) * FRAME_SAMPLES]
                .copy_from_slice(&arr_out);
        }

        // Skip first two frames for filter settling.
        let in_rms  = rms_q31(&input[FRAME_SAMPLES * 2..]);
        let out_rms = rms_q31(&output[FRAME_SAMPLES * 2..]);
        assert!(out_rms > in_rms * 0.5, "Round-trip lost too much energy: in={in_rms:.4} out={out_rms:.4}");
        assert!(out_rms < in_rms * 2.0, "Round-trip amplified: in={in_rms:.4} out={out_rms:.4}");
    }

    // ---------------------------------------------------------------------------
    // Conversion helpers
    // ---------------------------------------------------------------------------

    #[test]
    fn test_adc_to_q31_midscale() {
        // ADC midscale (2048) → 0
        assert_eq!(adc_to_q31(2048), 0);
    }

    #[test]
    fn test_adc_to_q31_max() {
        // ADC full scale (4095) → positive Q31 value
        let v = adc_to_q31(4095);
        assert!(v > 0);
    }

    #[test]
    fn test_q31_f32_roundtrip() {
        for &x in &[0.0f32, 0.5, -0.5, 0.999, -0.999] {
            let q = f32_to_q31(x);
            let back = q31_to_f32(q);
            assert!((back - x).abs() < 1e-6, "round-trip failed for {x}: got {back}");
        }
    }
}
