// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025-2026 Christian Riesch, christian@riesch.at
//
// dsp.rs — Digital signal processing pipeline.
//
// Called from the DSP Embassy task whenever the DMA half/full-transfer ISR
// sets PROCESS_FIRST_HALF or PROCESS_SECOND_HALF.
//
// Pipeline per half-buffer (FRAME_SAMPLES = 100 ADC samples at 200 kHz):
//
//   adc_to_q31()         100 × u16  →  100 × i32 (Q31, DC-centred)
//   fir_decimate()       100 × i32  →   10 × i32 (Q31, 20 kHz)
//   q31_to_f32()          10 × i32  →   10 × f32
//   iir_highpass()        10 × f32  →   10 × f32 (Chebyshev I HP, 200 Hz)
//   compress()            10 × f32  →   10 × f32 (envelope follower, 4:1 ratio)
//   iir_lowpass()         10 × f32  →   10 × f32 (Chebyshev I LP, 2800 Hz)
//   ssb_filter()          10 × f32  →  (10 × f32 I, 10 × f32 Q) analytic signal
//   f32_to_q31()         (10 × I, 10 × Q) f32  →  (10 × I, 10 × Q) Q31
//   fir_interpolate()    (10 × Q31 I, 10 × Q31 Q)  →  (100 × Q31 I, 100 × Q31 Q)
//   [cordic + outphasing]  (100 × I, 100 × Q) Q31  →  100 × PwmSample — TODO
//   write HRTIM ping-pong buffer half

use embassy_stm32::pac;

use crate::config::{FRAME_SAMPLES, PWM_PERIOD, TIMERC_PERIOD};
use crate::hrtim::{
    adc_buf_first_half, adc_buf_second_half,
    hrtim_buf_first_half_mut, hrtim_buf_second_half_mut,
    PwmSample,
};

// ---------------------------------------------------------------------------
// CORDIC outphasing constants
// ---------------------------------------------------------------------------

/// Transmission amplitude — sets the PA supply voltage via the buck converter.
/// Expressed in Timer C ticks (TIMERC_PERIOD = 850).  Higher = more TX power.
const AMPLITUDE: u32 = TIMERC_PERIOD / 2; // = 425 ticks

// ---------------------------------------------------------------------------
// FIR filter constants
// Generated by tools/design_decimate_filter.ipynb — do not edit manually.
// ---------------------------------------------------------------------------

const FIR_DECIMATE_FACTOR: usize = 10;
const FIR_NUM_TAPS:        usize = 60;

/// Number of output samples per half-buffer after 10:1 decimation.
const DECIMATED_LEN: usize = FRAME_SAMPLES / FIR_DECIMATE_FACTOR; // 10

/// FIR lowpass coefficients in Q31, time-reversed for direct convolution.
/// Cutoff 5 kHz, Hamming window.  Shared for both decimation and interpolation.
#[rustfmt::skip]
const FIR_COEFFS_Q31: [i32; FIR_NUM_TAPS] = [
      -1890794,
      -1971130,
      -2123936,
      -2324026,
      -2525779,
      -2663835,
      -2655228,
      -2402891,
      -1800394,
       -737704,
        892341,
       3187185,
       6227709,
      10071807,
      14748755,
      20254744,
      26549872,
      33556841,
      41161496,
      49215254,
      57539380,
      65930935,
      74170157,
      82028943,
      89280014,
      95706338,
     101110327,
     105322362,
     108208197,
     109674881,
     109674881,
     108208197,
     105322362,
     101110327,
      95706338,
      89280014,
      82028943,
      74170157,
      65930935,
      57539380,
      49215254,
      41161496,
      33556841,
      26549872,
      20254744,
      14748755,
      10071807,
       6227709,
       3187185,
        892341,
       -737704,
      -1800394,
      -2402891,
      -2655228,
      -2663835,
      -2525779,
      -2324026,
      -2123936,
      -1971130,
      -1890794,
];

/// Number of polyphase sub-filter taps: FIR_NUM_TAPS / FIR_DECIMATE_FACTOR.
const FIR_SUBFILTER_TAPS: usize = FIR_NUM_TAPS / FIR_DECIMATE_FACTOR; // 6

// ---------------------------------------------------------------------------
// Audio IIR filter constants
// Generated by tools/design_audio_filters.ipynb — do not edit manually.
// ---------------------------------------------------------------------------

/// Number of biquad sections in the highpass filter.
const HIGHPASS_STAGES: usize = 2;

/// Highpass filter coefficients: [[b0, b1, b2, -a1, -a2]; 2] in f32.
/// Direct Form II Transposed, normalised by a0.
/// Cutoff 200 Hz, Chebyshev I order 4, 0.3 dB ripple.
#[rustfmt::skip]
const HIGHPASS_COEFFS: [[f32; 5]; HIGHPASS_STAGES] = [
    [8.8843882084e-01, -1.7768776417e+00, 8.8843882084e-01, 1.8572715521e+00, -8.6588841677e-01],
    [1.0000000000e+00, -2.0000000000e+00, 1.0000000000e+00, 1.9743645191e+00, -9.7780704498e-01],
];

/// Number of biquad sections in the lowpass filter.
const LOWPASS_STAGES: usize = 2;

/// Lowpass filter coefficients: [[b0, b1, b2, -a1, -a2]; 2] in f32.
/// Direct Form II Transposed, normalised by a0.
/// Cutoff 2800 Hz, Chebyshev I order 4, 0.3 dB ripple.
#[rustfmt::skip]
const LOWPASS_COEFFS: [[f32; 5]; LOWPASS_STAGES] = [
    [1.0223765858e-02, 2.0447531715e-02, 1.0223765858e-02, 1.1647846699e+00, -4.0787613392e-01],
    [1.0000000000e+00, 2.0000000000e+00, 1.0000000000e+00, 1.0389341116e+00, -7.3549830914e-01],
];

// ---------------------------------------------------------------------------
// FIR decimation filter
// ---------------------------------------------------------------------------

/// Single-channel FIR decimation filter (200 kHz → 20 kHz, factor 10).
///
/// Holds the persistent overlap state between successive half-buffer calls
/// (NUM_TAPS − 1 = 59 samples).  All arithmetic in Q31 using i64 accumulators
/// so that LLVM emits SMULL/SMLAL on Cortex-M4.
struct FirDecimate {
    /// Last NUM_TAPS−1 input samples carried over from the previous call.
    state: [i32; FIR_NUM_TAPS - 1],
}

impl FirDecimate {
    const fn new() -> Self {
        Self { state: [0i32; FIR_NUM_TAPS - 1] }
    }

    /// Decimate `input` (FRAME_SAMPLES Q31 samples) to DECIMATED_LEN Q31 samples.
    ///
    /// Algorithm:
    ///   1. Concatenate `state` (59 samples) and `input` (100 samples) into a
    ///      159-element working window.
    ///   2. For each of the 10 output samples, compute one dot product of
    ///      FIR_NUM_TAPS = 60 coefficients × the corresponding window slice.
    ///   3. Right-shift the i64 accumulator by 31 to return to Q31, then
    ///      saturate to i32.
    ///   4. Update state = last FIR_NUM_TAPS−1 samples of `input`.
    fn process(
        &mut self,
        input: &[i32; FRAME_SAMPLES],
    ) -> [i32; DECIMATED_LEN] {
        // Working buffer: [old state (59) || new input (100)] = 159 samples.
        let mut buf = [0i32; FIR_NUM_TAPS - 1 + FRAME_SAMPLES];
        buf[..FIR_NUM_TAPS - 1].copy_from_slice(&self.state);
        buf[FIR_NUM_TAPS - 1..].copy_from_slice(input);

        let mut output = [0i32; DECIMATED_LEN];
        for k in 0..DECIMATED_LEN {
            let start = k * FIR_DECIMATE_FACTOR;
            // i64 accumulator avoids overflow during the 60-tap MAC.
            let acc: i64 = FIR_COEFFS_Q31
                .iter()
                .zip(buf[start..start + FIR_NUM_TAPS].iter())
                .map(|(&c, &x)| c as i64 * x as i64)
                .sum();
            // Q2.62 → Q1.31: shift right 31 bits, saturate to i32.
            output[k] = (acc >> 31).clamp(i32::MIN as i64, i32::MAX as i64) as i32;
        }

        // Carry the last FIR_NUM_TAPS−1 samples forward as the new state.
        self.state.copy_from_slice(&buf[FRAME_SAMPLES..]);

        output
    }
}

// ---------------------------------------------------------------------------
// FIR interpolation filter (Q31)
// ---------------------------------------------------------------------------

/// Single-channel FIR interpolation filter (20 kHz → 200 kHz, factor 10), Q31.
///
/// Shares the same 60-tap Q31 prototype as the decimator, decomposed into 10
/// polyphase sub-filters of 6 taps each.  All arithmetic uses i64 accumulators
/// so that LLVM emits SMULL/SMLAL on Cortex-M4.
///
/// Polyphase output for input x[k], phase p (0..9):
///   y[k×10 + p] = 10 × Σ h[p + n×10] × x[k−n]   for n = 0..5
///
/// The factor 10 compensates for the 1/L power loss from zero-insertion.
/// Output is saturated to i32 Q31.
struct FirInterpolate {
    /// Last FIR_SUBFILTER_TAPS−1 = 5 input samples, oldest at index 0.
    state: [i32; FIR_SUBFILTER_TAPS - 1],
}

impl FirInterpolate {
    const fn new() -> Self {
        Self { state: [0i32; FIR_SUBFILTER_TAPS - 1] }
    }

    /// Interpolate `input` (DECIMATED_LEN Q31 samples) to FRAME_SAMPLES Q31.
    fn process(
        &mut self,
        input:  &[i32; DECIMATED_LEN],
        output: &mut [i32; FRAME_SAMPLES],
    ) {
        // Working buffer: [old state (5) || new input (10)] = 15 samples.
        let mut buf = [0i32; FIR_SUBFILTER_TAPS - 1 + DECIMATED_LEN];
        buf[..FIR_SUBFILTER_TAPS - 1].copy_from_slice(&self.state);
        buf[FIR_SUBFILTER_TAPS - 1..].copy_from_slice(input);

        for k in 0..DECIMATED_LEN {
            for p in 0..FIR_DECIMATE_FACTOR {
                // i64 accumulator for the 6-tap polyphase dot product.
                let mut acc = 0i64;
                for n in 0..FIR_SUBFILTER_TAPS {
                    // Prototype tap for phase p, sub-tap n (time-reversed):
                    // coeff = FIR_COEFFS_Q31[N−1 − p − n×L]
                    let c = FIR_COEFFS_Q31[FIR_NUM_TAPS - 1 - p - n * FIR_DECIMATE_FACTOR];
                    let x = buf[k + FIR_SUBFILTER_TAPS - 1 - n];
                    acc += c as i64 * x as i64;
                }
                // Scale by L=10 (compensate zero-insertion), then Q2.62 → Q1.31.
                let scaled = acc * FIR_DECIMATE_FACTOR as i64;
                output[k * FIR_DECIMATE_FACTOR + p] =
                    (scaled >> 31).clamp(i32::MIN as i64, i32::MAX as i64) as i32;
            }
        }

        // Save the last FIR_SUBFILTER_TAPS−1 input samples as new state.
        self.state.copy_from_slice(&buf[DECIMATED_LEN..]);
    }
}

// ---------------------------------------------------------------------------
// IIR biquad filter — Direct Form II Transposed, single-precision f32
// ---------------------------------------------------------------------------

/// Cascaded biquad filter with N sections, f32 arithmetic.
///
/// Each section stores coefficients as `[b0, b1, b2, -a1, -a2]` (normalised
/// by a0, a coefficients sign-negated so the update is a pure accumulate).
/// State per section: two delay elements `[s0, s1]`.
struct BiquadState<const N: usize> {
    s: [[f32; 2]; N],
}

impl<const N: usize> BiquadState<N> {
    const fn new() -> Self {
        Self { s: [[0.0f32; 2]; N] }
    }

    /// Process `input` through all N biquad sections in-place into `output`.
    ///
    /// Direct Form II Transposed update per section:
    ///   y    = b0·x + s0
    ///   s0  ← b1·x + na1·y + s1
    ///   s1  ← b2·x + na2·y
    fn process(
        &mut self,
        coeffs: &[[f32; 5]; N],
        input: &[f32; DECIMATED_LEN],
        output: &mut [f32; DECIMATED_LEN],
    ) {
        for (i, &x) in input.iter().enumerate() {
            let mut y = x;
            for (s, c) in self.s.iter_mut().zip(coeffs.iter()) {
                let [b0, b1, b2, na1, na2] = *c;
                let xin = y;
                y     = b0 * xin + s[0];
                s[0]  = b1 * xin + na1 * y + s[1];
                s[1]  = b2 * xin + na2 * y;
            }
            output[i] = y;
        }
    }
}

// ---------------------------------------------------------------------------
// Voice compressor
// ---------------------------------------------------------------------------

/// Compression threshold — envelope level above which gain reduction begins.
const COMP_THRESHOLD:   f32 = 0.3;
/// Compression ratio (4:1 — for every 4 dB over threshold, output rises 1 dB).
const COMP_RATIO:       f32 = 4.0;
/// Make-up gain applied after compression.
const COMP_MAKEUP_GAIN: f32 = 1.5;

/// Attack coefficient: 1 − exp(−1 / (FS × COMP_ATTACK))
/// where FS = 20 000 Hz, COMP_ATTACK = 0.0002 s → exp(−0.25)
const COMP_ATTACK_COEFF:  f32 = 0.22119922_f32;
/// Release coefficient: 1 − exp(−1 / (FS × COMP_RELEASE))
/// where FS = 20 000 Hz, COMP_RELEASE = 0.1 s → exp(−0.0005)
const COMP_RELEASE_COEFF: f32 = 0.00049987503_f32;

/// Per-call state for the envelope follower / gain computer.
struct Compressor {
    envelope: f32,
    gain:     f32,
}

impl Compressor {
    const fn new() -> Self {
        Self { envelope: 0.0, gain: 1.0 }
    }

    fn process(
        &mut self,
        input:  &[f32; DECIMATED_LEN],
        output: &mut [f32; DECIMATED_LEN],
    ) {
        for (out, &sample) in output.iter_mut().zip(input.iter()) {
            let abs_sample = if sample < 0.0 { -sample } else { sample };

            // Envelope follower with asymmetric attack / release.
            if abs_sample > self.envelope {
                self.envelope += COMP_ATTACK_COEFF  * (abs_sample - self.envelope);
            } else {
                self.envelope += COMP_RELEASE_COEFF * (abs_sample - self.envelope);
            }

            // Compute gain — reduce above threshold according to ratio.
            if self.envelope > COMP_THRESHOLD {
                let overshoot   = self.envelope / COMP_THRESHOLD;
                let compressed  = 1.0 + (overshoot - 1.0) / COMP_RATIO;
                self.gain       = COMP_THRESHOLD * compressed / self.envelope;
            } else {
                self.gain = 1.0;
            }

            // Apply compression + make-up gain, then hard-limit to ±1.
            let s = sample * self.gain * COMP_MAKEUP_GAIN;
            *out = s.clamp(-1.0, 1.0);
        }
    }
}

// ---------------------------------------------------------------------------
// SSB analytic FIR filter constants
// Generated by tools/design_ssb_filter.ipynb — do not edit manually.
// ---------------------------------------------------------------------------

/// Total length of the SSB analytic FIR shift register.
const SSB_FILTER_TAPS: usize = 257;

/// Number of non-zero taps in the I (real) path — even indices of the full filter.
const SSB_REAL_TAPS: usize = 129;

/// Number of non-zero taps in the Q (imaginary) path — odd indices of the full filter.
const SSB_IMAG_TAPS: usize = 128;

/// I-path compact coefficients: full_filter[0, 2, 4, …, 256].
/// Applied with stride-2 over the shared shift register starting at index 0.
/// Passband 530–9470 Hz at 20 kHz, 257-tap Remez equiripple.
#[rustfmt::skip]
const SSB_REAL_COEFFS: [f32; SSB_REAL_TAPS] = [
    -1.0015372709e-06,  2.2930228170e-06,  3.3461501516e-06,  5.2559112191e-06,
     7.7128152043e-06,  1.0480947822e-05,  1.3278330698e-05,  1.5694196918e-05,
     1.7181313524e-05,  1.7058382582e-05,  1.4531447960e-05,  8.7336657089e-06,
    -1.2160819551e-06, -1.6135949409e-05, -3.6687335523e-05, -6.3266161305e-05,
    -9.5884810435e-05, -1.3405329082e-04, -1.7667168868e-04, -2.2194175108e-04,
    -2.6730718673e-04, -3.0943291495e-04, -3.4423696343e-04, -3.6698704935e-04,
    -3.7246421562e-04, -3.5518512595e-04, -3.0968984356e-04, -2.3093081836e-04,
    -1.1463979172e-04,  4.2201892938e-05,  2.4092476815e-04,  4.8072510981e-04,
     7.5826630928e-04,  1.0673451470e-03,  1.3986598933e-03,  1.7397002084e-03,
     2.0747862291e-03,  2.3852747399e-03,  2.6499389205e-03,  2.8455299325e-03,
     2.9475032352e-03,  2.9309017118e-03,  2.7713598683e-03,  2.4461979046e-03,
     1.9355559489e-03,  1.2235176982e-03,  2.9917375650e-04, -8.4243499441e-04,
    -2.1995522548e-03, -3.7631618325e-03, -5.5167032406e-03, -7.4360873550e-03,
    -9.4900242984e-03, -1.1640660465e-02, -1.3844528235e-02, -1.6053767875e-02,
    -1.8217587844e-02, -2.0283894613e-02, -2.2201064974e-02, -2.3919727653e-02,
    -2.5394538417e-02, -2.6585834101e-02, -2.7461096644e-02, -2.7996178716e-02,
     4.7182378173e-01, -2.7996178716e-02, -2.7461096644e-02, -2.6585834101e-02,
    -2.5394538417e-02, -2.3919727653e-02, -2.2201064974e-02, -2.0283894613e-02,
    -1.8217587844e-02, -1.6053767875e-02, -1.3844528235e-02, -1.1640660465e-02,
    -9.4900242984e-03, -7.4360873550e-03, -5.5167032406e-03, -3.7631618325e-03,
    -2.1995522548e-03, -8.4243499441e-04,  2.9917375650e-04,  1.2235176982e-03,
     1.9355559489e-03,  2.4461979046e-03,  2.7713598683e-03,  2.9309017118e-03,
     2.9475032352e-03,  2.8455299325e-03,  2.6499389205e-03,  2.3852747399e-03,
     2.0747862291e-03,  1.7397002084e-03,  1.3986598933e-03,  1.0673451470e-03,
     7.5826630928e-04,  4.8072510981e-04,  2.4092476815e-04,  4.2201892938e-05,
    -1.1463979172e-04, -2.3093081836e-04, -3.0968984356e-04, -3.5518512595e-04,
    -3.7246421562e-04, -3.6698704935e-04, -3.4423696343e-04, -3.0943291495e-04,
    -2.6730718673e-04, -2.2194175108e-04, -1.7667168868e-04, -1.3405329082e-04,
    -9.5884810435e-05, -6.3266161305e-05, -3.6687335523e-05, -1.6135949409e-05,
    -1.2160819551e-06,  8.7336657089e-06,  1.4531447960e-05,  1.7058382582e-05,
     1.7181313524e-05,  1.5694196918e-05,  1.3278330698e-05,  1.0480947822e-05,
     7.7128152043e-06,  5.2559112191e-06,  3.3461501516e-06,  2.2930228170e-06,
    -1.0015372709e-06,
];

/// Q-path compact coefficients: full_filter[1, 3, 5, …, 255].
/// Applied with stride-2 over the shared shift register starting at index 1.
/// Passband 530–9470 Hz at 20 kHz, 257-tap Remez equiripple.
#[rustfmt::skip]
const SSB_IMAG_COEFFS: [f32; SSB_IMAG_TAPS] = [
    -3.3779708701e-06, -1.9478195554e-06, -1.9168621748e-06, -1.2431479490e-06,
     3.5058798176e-07,  3.1770571240e-06,  7.5202710832e-06,  1.3611955183e-05,
     2.1579917302e-05,  3.1393814425e-05,  4.2810101149e-05,  5.5321052059e-05,
     6.8112261943e-05,  8.0034253187e-05,  8.9595356258e-05,  9.4980954600e-05,
     9.4105933385e-05,  8.4704472101e-05,  6.4458290581e-05,  3.1157334888e-05,
    -1.7107584426e-05, -8.1721678725e-05, -1.6330594372e-04, -2.6148100733e-04,
    -3.7464901106e-04, -4.9979775213e-04, -6.3234107802e-04, -7.6608348172e-04,
    -8.9319678955e-04, -1.0043596849e-03, -1.0889746482e-03, -1.1355153983e-03,
    -1.1319892947e-03, -1.0665055597e-03, -9.2794105876e-04, -7.0667639375e-04,
    -3.9537489647e-04,  1.0225045116e-05,  5.1055062795e-04,  1.1014989577e-03,
     1.7738512252e-03,  2.5128242560e-03,  3.2977983356e-03,  4.1022370569e-03,
     4.8938053660e-03,  5.6346827187e-03,  6.2820408493e-03,  6.7886435427e-03,
     7.1034799330e-03,  7.1723107249e-03,  6.9379662164e-03,  6.3401162624e-03,
     5.3141033277e-03,  3.7881801836e-03,  1.6779416474e-03, -1.1242580367e-03,
    -4.7694551758e-03, -9.4918282703e-03, -1.5692636371e-02, -2.4136526510e-02,
    -3.6484256387e-02, -5.7102695107e-02, -1.0211124271e-01, -3.1696969271e-01,
     3.1696969271e-01,  1.0211124271e-01,  5.7102695107e-02,  3.6484256387e-02,
     2.4136526510e-02,  1.5692636371e-02,  9.4918282703e-03,  4.7694551758e-03,
     1.1242580367e-03, -1.6779416474e-03, -3.7881801836e-03, -5.3141033277e-03,
    -6.3401162624e-03, -6.9379662164e-03, -7.1723107249e-03, -7.1034799330e-03,
    -6.7886435427e-03, -6.2820408493e-03, -5.6346827187e-03, -4.8938053660e-03,
    -4.1022370569e-03, -3.2977983356e-03, -2.5128242560e-03, -1.7738512252e-03,
    -1.1014989577e-03, -5.1055062795e-04, -1.0225045116e-05,  3.9537489647e-04,
     7.0667639375e-04,  9.2794105876e-04,  1.0665055597e-03,  1.1319892947e-03,
     1.1355153983e-03,  1.0889746482e-03,  1.0043596849e-03,  8.9319678955e-04,
     7.6608348172e-04,  6.3234107802e-04,  4.9979775213e-04,  3.7464901106e-04,
     2.6148100733e-04,  1.6330594372e-04,  8.1721678725e-05,  1.7107584426e-05,
    -3.1157334888e-05, -6.4458290581e-05, -8.4704472101e-05, -9.4105933385e-05,
    -9.4980954600e-05, -8.9595356258e-05, -8.0034253187e-05, -6.8112261943e-05,
    -5.5321052059e-05, -4.2810101149e-05, -3.1393814425e-05, -2.1579917302e-05,
    -1.3611955183e-05, -7.5202710832e-06, -3.1770571240e-06, -3.5058798176e-07,
     1.2431479490e-06,  1.9168621748e-06,  1.9478195554e-06,  3.3779708701e-06,
];

// ---------------------------------------------------------------------------
// SSB analytic FIR filter
// ---------------------------------------------------------------------------

/// Complex analytic FIR filter producing I and Q from a real audio signal.
///
/// Shares a single 257-sample shift register for both paths.  With
/// `state[0]` holding the newest sample and `state[256]` the oldest:
///
///   I[n] = Σ SSB_REAL_COEFFS[j] · state[2j]   for j = 0 … SSB_REAL_TAPS−1
///   Q[n] = Σ SSB_IMAG_COEFFS[j] · state[2j+1] for j = 0 … SSB_IMAG_TAPS−1
///
/// This works because j^k is real for even k and imaginary for odd k, so the
/// real and imaginary parts of the analytic filter coefficient array
/// interleave with no overlap.
struct SsbFilter {
    state: [f32; SSB_FILTER_TAPS],
}

impl SsbFilter {
    const fn new() -> Self {
        Self { state: [0.0f32; SSB_FILTER_TAPS] }
    }

    /// Process a block of `input` samples, writing I and Q output arrays.
    fn process(
        &mut self,
        input: &[f32; DECIMATED_LEN],
        i_out: &mut [f32; DECIMATED_LEN],
        q_out: &mut [f32; DECIMATED_LEN],
    ) {
        for k in 0..DECIMATED_LEN {
            // Insert new sample at the front; oldest sample falls off the end.
            self.state.copy_within(0..SSB_FILTER_TAPS - 1, 1);
            self.state[0] = input[k];

            // I path: dot product with even-indexed state entries.
            i_out[k] = SSB_REAL_COEFFS
                .iter()
                .zip(self.state.iter().step_by(2))
                .map(|(&c, &x)| c * x)
                .sum();

            // Q path: dot product with odd-indexed state entries.
            q_out[k] = SSB_IMAG_COEFFS
                .iter()
                .zip(self.state[1..].iter().step_by(2))
                .map(|(&c, &x)| c * x)
                .sum();
        }
    }
}

// ---------------------------------------------------------------------------
// Static filter instances — accessed only from the DSP task (single writer).
// ---------------------------------------------------------------------------
static mut DECIMATOR:      FirDecimate                  = FirDecimate::new();
static mut HP_FILTER:      BiquadState<HIGHPASS_STAGES> = BiquadState::new();
static mut COMPRESSOR:     Compressor                   = Compressor::new();
static mut LP_FILTER:      BiquadState<LOWPASS_STAGES>  = BiquadState::new();
static mut SSB_FILTER:     SsbFilter                    = SsbFilter::new();
static mut INTERP_I:       FirInterpolate               = FirInterpolate::new();
static mut INTERP_Q:       FirInterpolate               = FirInterpolate::new();

// ---------------------------------------------------------------------------
// Sample format conversion helpers
// ---------------------------------------------------------------------------

/// Convert a 12-bit right-aligned ADC sample (0 … 4095) to Q31.
///
/// Subtracts midscale (2048) to centre on zero, then shifts left by 19 to
/// fill the 31 significant bits of a Q31 value.
/// Output range: −2048 × 2¹⁹ = −1 073 741 824  …  2047 × 2¹⁹ = 1 073 217 536
#[inline]
fn adc_to_q31(sample: u16) -> i32 {
    (sample as i32 - 2048) << 19
}

/// Convert a Q31 sample to normalised f32 in the range [−1.0, 1.0).
#[inline]
fn q31_to_f32(sample: i32) -> f32 {
    sample as f32 * (1.0 / 2_147_483_648.0_f32)
}

/// Convert a normalised f32 sample in [−1.0, 1.0] to Q31.
///
/// Values outside [−1.0, 1.0] are saturated to i32::MIN / i32::MAX.
#[inline]
fn f32_to_q31(sample: f32) -> i32 {
    (sample * 2_147_483_648.0_f32).clamp(i32::MIN as f32, i32::MAX as f32) as i32
}

// ---------------------------------------------------------------------------
// CORDIC initialisation and per-sample calculation
// ---------------------------------------------------------------------------

/// Initialise the CORDIC peripheral for MODULUS function (Q1.31, 32-bit, 2 args / 2 results).
///
/// Must be called once during hardware init, before `process_first_half` /
/// `process_second_half`.  Uses PAC directly, consistent with HRTIM/ADC/DMA.
///
/// CORDIC config (matching C HAL `CORDIC_FUNCTION_MODULUS`):
///   Function  : MODULUS  (ARG1=I, ARG2=Q → RES1=|Z|, RES2=∠Z)
///   Scale     : 0        (no input/output scaling)
///   Precision : 15       (15 × 4 = 60 iterations, ≥ 19-bit accuracy)
///   ArgSize   : 32-bit   (Q1.31)
///   ResSize   : 32-bit   (Q1.31)
///   NbWrite   : 2        (one ARG1 + ARG2 write pair triggers a calculation)
///   NbRead    : 2        (read modulus then phase)
pub fn init() {
    // Enable CORDIC clock on AHB1.
    pac::RCC.ahb1enr().modify(|w| w.set_cordicen(true));
    // Brief reset to put CORDIC in a known state.
    pac::RCC.ahb1rstr().modify(|w| w.set_cordicrst(true));
    pac::RCC.ahb1rstr().modify(|w| w.set_cordicrst(false));

    pac::CORDIC.csr().write(|w| {
        w.set_func(pac::cordic::vals::Func::from_bits(3)); // MODULUS
        w.set_precision(pac::cordic::vals::Precision::from_bits(15)); // 60 iterations
        w.set_scale(pac::cordic::vals::Scale::from_bits(0)); // no scaling
        w.set_nargs(pac::cordic::vals::Num::NUM2); // write I then Q
        w.set_nres(pac::cordic::vals::Num::NUM2);  // read modulus then phase
        w.set_argsize(pac::cordic::vals::Size::BITS32);
        w.set_ressize(pac::cordic::vals::Size::BITS32);
    });
}

/// Blocking CORDIC MODULUS calculation: (I, Q) → (modulus, phase), all Q1.31.
///
/// Writes ARG1=I then ARG2=Q (ARG2 write triggers the calculation), then
/// reads modulus and phase once RRDY is set.
/// Typical latency: 60 CORDIC iterations ≈ 60 / SYSCLK ≈ 0.35 µs at 170 MHz.
#[inline]
fn cordic_modulus(i: i32, q: i32) -> (i32, i32) {
    pac::CORDIC.wdata().write_value(i as u32); // ARG1 = I (preloaded)
    pac::CORDIC.wdata().write_value(q as u32); // ARG2 = Q (triggers calc)
    while !pac::CORDIC.csr().read().rrdy() {}   // wait for result ready
    let modulus = pac::CORDIC.rdata().read() as i32; // primary result
    let phase   = pac::CORDIC.rdata().read() as i32; // secondary result
    (modulus, phase)
}

// ---------------------------------------------------------------------------
// Public pipeline entry points — called from the DSP Embassy task
// ---------------------------------------------------------------------------

/// Process the first half of the ADC ping-pong buffer (samples 0..FRAME_SAMPLES).
/// Writes results to the first half of the HRTIM ping-pong buffer.
///
/// # Safety
/// Must be called only from the context that owns the first buffer half
/// (i.e. after the DMA half-transfer flag has been set).
pub unsafe fn process_first_half() {
    let adc = adc_buf_first_half();
    let hrtim_out = hrtim_buf_first_half_mut();
    process_half(adc, hrtim_out);
}

/// Process the second half of the ADC ping-pong buffer (samples FRAME_SAMPLES..2×FRAME_SAMPLES).
/// Writes results to the second half of the HRTIM ping-pong buffer.
///
/// # Safety
/// Must be called only after the DMA transfer-complete flag has been set.
pub unsafe fn process_second_half() {
    let adc = adc_buf_second_half();
    let hrtim_out = hrtim_buf_second_half_mut();
    process_half(adc, hrtim_out);
}

// ---------------------------------------------------------------------------
// Internal pipeline implementation
// ---------------------------------------------------------------------------

/// Core pipeline: process one half-buffer of ADC samples into PwmSamples.
///
/// `adc_in`   : FRAME_SAMPLES raw ADC u16 samples (200 kHz)
/// `hrtim_out`: FRAME_SAMPLES PwmSample destination (200 kHz)
fn process_half(adc_in: &[u16], hrtim_out: &mut [PwmSample]) {
    debug_assert_eq!(adc_in.len(),    FRAME_SAMPLES);
    debug_assert_eq!(hrtim_out.len(), FRAME_SAMPLES);

    // --- Stage 1: convert ADC u16 → Q31 ---
    let mut q31_in = [0i32; FRAME_SAMPLES];
    for (dst, &src) in q31_in.iter_mut().zip(adc_in.iter()) {
        *dst = adc_to_q31(src);
    }

    // --- Stage 2: 10:1 FIR decimation → 10 Q31 samples at 20 kHz ---
    // Safety: static filters are only accessed from this function,
    // which is called exclusively from the single DSP task.
    let q31_in_arr: &[i32; FRAME_SAMPLES] =
        (&q31_in as &[i32]).try_into().unwrap();
    let decimated: [i32; DECIMATED_LEN] =
        unsafe { DECIMATOR.process(q31_in_arr) };

    // --- Stage 3a: Q31 → f32 ---
    let mut audio = [0.0f32; DECIMATED_LEN];
    for (dst, &src) in audio.iter_mut().zip(decimated.iter()) {
        *dst = q31_to_f32(src);
    }

    // --- Stage 3b: high-pass IIR (Chebyshev I, 200 Hz) ---
    let mut hp_out = [0.0f32; DECIMATED_LEN];
    unsafe { HP_FILTER.process(&HIGHPASS_COEFFS, &audio, &mut hp_out) };

    // --- Stage 3c: compression ---
    let mut compressed = [0.0f32; DECIMATED_LEN];
    unsafe { COMPRESSOR.process(&hp_out, &mut compressed) };

    // --- Stage 3d: low-pass IIR (Chebyshev I, 2800 Hz) ---
    let mut lp_out = [0.0f32; DECIMATED_LEN];
    unsafe { LP_FILTER.process(&LOWPASS_COEFFS, &compressed, &mut lp_out) };

    // `lp_out` holds 10 band-limited audio samples in f32 at 20 kHz.

    // --- Stage 4: SSB analytic FIR → I and Q paths ---
    let mut ssb_i = [0.0f32; DECIMATED_LEN];
    let mut ssb_q = [0.0f32; DECIMATED_LEN];
    unsafe { SSB_FILTER.process(&lp_out, &mut ssb_i, &mut ssb_q) };

    // `ssb_i` and `ssb_q` are the analytic signal components at 20 kHz.
    // USB = ssb_i;  LSB = ssb_i with ssb_q negated.

    // --- Stage 5a: f32 → Q31 (before interpolation, avoid conversion at 200 kHz) ---
    let mut q31_i = [0i32; DECIMATED_LEN];
    let mut q31_q = [0i32; DECIMATED_LEN];
    for (dst, &src) in q31_i.iter_mut().zip(ssb_i.iter()) {
        *dst = f32_to_q31(src);
    }
    for (dst, &src) in q31_q.iter_mut().zip(ssb_q.iter()) {
        *dst = f32_to_q31(src);
    }

    // --- Stage 5b: 10:1 Q31 FIR interpolation → 100 Q31 samples at 200 kHz ---
    let mut interp_i = [0i32; FRAME_SAMPLES];
    let mut interp_q = [0i32; FRAME_SAMPLES];
    unsafe {
        INTERP_I.process(&q31_i, &mut interp_i);
        INTERP_Q.process(&q31_q, &mut interp_q);
    }

    // `interp_i` and `interp_q` are Q31 at 200 kHz, ready for CORDIC.

    // --- Stage 5c: CORDIC polar conversion + outphasing → HRTIM compare values ---
    //
    // CORDIC MODULUS maps (I, Q) → (modulus, phase), both Q1.31.
    //   modulus : magnitude of the analytic signal, range [0, 1)
    //   phase   : phase angle, range [-1, +1) representing [-π, +π)
    //
    // Timer C CMP1 (buck converter duty → PA supply voltage):
    //   Scales modulus Q1.31 to [3, AMPLITUDE] TIMERC ticks.
    //   (modulus >> 15) gives ~Q1.15; × AMPLITUDE >> 16 gives integer ticks.
    //   Hard minimum of 3: HRTIM does not allow triggers in the first 3 ticks.
    //
    // Timer A/B CMP1 (outphasing angle):
    //   Maps phase [-1, +1] (= [-π, +π]) to a tick offset in [0, PWM_PERIOD).
    //   Phase is negated: a positive phase means an earlier crossover, so the
    //   negation maps the signal phase correctly to the HRTIM timing.
    //   CMP2 = (CMP1 + PWM_PERIOD/2) % PWM_PERIOD maintains 180° complement.
    for (i, slot) in hrtim_out.iter_mut().enumerate() {
        let (modulus, phase) = cordic_modulus(interp_i[i], interp_q[i]);

        // Timer C CMP1: modulus → PA bias ticks.
        let mag = (((modulus as i64) >> 15) * AMPLITUDE as i64) >> 16;
        let tc_cmp1 = (mag as u32).clamp(3, AMPLITUDE);

        // Timer A/B CMP1/CMP2: phase → outphasing angle in PWM ticks.
        let phase_ticks =
            (((-(phase as i64)) >> 15) * (PWM_PERIOD as i64 / 2) >> 16)
            + PWM_PERIOD as i64 / 2;
        let ta_cmp1 = (phase_ticks as u32) % PWM_PERIOD;
        let ta_cmp2 = (ta_cmp1 + PWM_PERIOD / 2) % PWM_PERIOD;

        *slot = PwmSample {
            tim_a_cmp1: ta_cmp1,
            tim_a_cmp2: ta_cmp2,
            tim_b_cmp1: ta_cmp1,
            tim_b_cmp2: ta_cmp2,
            tim_c_cmp1: tc_cmp1,
        };
    }
}
