// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025-2026 Christian Riesch, christian@riesch.at
//
// dsp.rs — Digital signal processing pipeline.
//
// Called from the DSP Embassy task whenever the DMA half/full-transfer ISR
// sets PROCESS_FIRST_HALF or PROCESS_SECOND_HALF.
//
// Pipeline per half-buffer (FRAME_SAMPLES = 100 ADC samples at 200 kHz):
//
//   adc_to_q31()         100 × u16  →  100 × i32 (Q31, DC-centred)
//   fir_decimate()       100 × i32  →   10 × i32 (Q31, 20 kHz)
//   [audio IIR + compression — TODO]
//   [Hilbert / SSB modulation — TODO]
//   [fir_interpolate()]   10 × i32  →  100 × PwmSample (200 kHz) — TODO
//   write HRTIM ping-pong buffer half

use crate::config::FRAME_SAMPLES;
use crate::hrtim::{
    adc_buf_first_half, adc_buf_second_half,
    hrtim_buf_first_half_mut, hrtim_buf_second_half_mut,
    PwmSample,
};

// ---------------------------------------------------------------------------
// FIR filter constants
// Generated by tools/design_decimate_filter.py — do not edit manually.
// ---------------------------------------------------------------------------

const FIR_DECIMATE_FACTOR: usize = 10;
const FIR_NUM_TAPS:        usize = 60;

/// Number of output samples per half-buffer after 10:1 decimation.
const DECIMATED_LEN: usize = FRAME_SAMPLES / FIR_DECIMATE_FACTOR; // 10

/// FIR lowpass coefficients in Q31, time-reversed for direct convolution.
/// Cutoff 5 kHz, Hamming window.  Shared for both decimation and interpolation.
#[rustfmt::skip]
const FIR_COEFFS_Q31: [i32; FIR_NUM_TAPS] = [
      -1890794,
      -1971130,
      -2123936,
      -2324026,
      -2525779,
      -2663835,
      -2655228,
      -2402891,
      -1800394,
       -737704,
        892341,
       3187185,
       6227709,
      10071807,
      14748755,
      20254744,
      26549872,
      33556841,
      41161496,
      49215254,
      57539380,
      65930935,
      74170157,
      82028943,
      89280014,
      95706338,
     101110327,
     105322362,
     108208197,
     109674881,
     109674881,
     108208197,
     105322362,
     101110327,
      95706338,
      89280014,
      82028943,
      74170157,
      65930935,
      57539380,
      49215254,
      41161496,
      33556841,
      26549872,
      20254744,
      14748755,
      10071807,
       6227709,
       3187185,
        892341,
       -737704,
      -1800394,
      -2402891,
      -2655228,
      -2663835,
      -2525779,
      -2324026,
      -2123936,
      -1971130,
      -1890794,
];

// ---------------------------------------------------------------------------
// FIR decimation filter
// ---------------------------------------------------------------------------

/// Single-channel FIR decimation filter (200 kHz → 20 kHz, factor 10).
///
/// Holds the persistent overlap state between successive half-buffer calls
/// (NUM_TAPS − 1 = 59 samples).  All arithmetic in Q31 using i64 accumulators
/// so that LLVM emits SMULL/SMLAL on Cortex-M4.
struct FirDecimate {
    /// Last NUM_TAPS−1 input samples carried over from the previous call.
    state: [i32; FIR_NUM_TAPS - 1],
}

impl FirDecimate {
    const fn new() -> Self {
        Self { state: [0i32; FIR_NUM_TAPS - 1] }
    }

    /// Decimate `input` (FRAME_SAMPLES Q31 samples) to DECIMATED_LEN Q31 samples.
    ///
    /// Algorithm:
    ///   1. Concatenate `state` (59 samples) and `input` (100 samples) into a
    ///      159-element working window.
    ///   2. For each of the 10 output samples, compute one dot product of
    ///      FIR_NUM_TAPS = 60 coefficients × the corresponding window slice.
    ///   3. Right-shift the i64 accumulator by 31 to return to Q31, then
    ///      saturate to i32.
    ///   4. Update state = last FIR_NUM_TAPS−1 samples of `input`.
    fn process(
        &mut self,
        input: &[i32; FRAME_SAMPLES],
    ) -> [i32; DECIMATED_LEN] {
        // Working buffer: [old state (59) || new input (100)] = 159 samples.
        let mut buf = [0i32; FIR_NUM_TAPS - 1 + FRAME_SAMPLES];
        buf[..FIR_NUM_TAPS - 1].copy_from_slice(&self.state);
        buf[FIR_NUM_TAPS - 1..].copy_from_slice(input);

        let mut output = [0i32; DECIMATED_LEN];
        for k in 0..DECIMATED_LEN {
            let start = k * FIR_DECIMATE_FACTOR;
            // i64 accumulator avoids overflow during the 60-tap MAC.
            let acc: i64 = FIR_COEFFS_Q31
                .iter()
                .zip(buf[start..start + FIR_NUM_TAPS].iter())
                .map(|(&c, &x)| c as i64 * x as i64)
                .sum();
            // Q2.62 → Q1.31: shift right 31 bits, saturate to i32.
            output[k] = (acc >> 31).clamp(i32::MIN as i64, i32::MAX as i64) as i32;
        }

        // Carry the last FIR_NUM_TAPS−1 samples forward as the new state.
        self.state.copy_from_slice(&buf[FRAME_SAMPLES..]);

        output
    }
}

// ---------------------------------------------------------------------------
// Static filter instance — accessed only from the DSP task (single writer).
// ---------------------------------------------------------------------------
static mut DECIMATOR: FirDecimate = FirDecimate::new();

// ---------------------------------------------------------------------------
// ADC sample conversion
// ---------------------------------------------------------------------------

/// Convert a 12-bit right-aligned ADC sample (0 … 4095) to Q31.
///
/// Subtracts midscale (2048) to centre on zero, then shifts left by 19 to
/// fill the 31 significant bits of a Q31 value.
/// Output range: −2048 × 2¹⁹ = −1 073 741 824  …  2047 × 2¹⁹ = 1 073 217 536
#[inline]
fn adc_to_q31(sample: u16) -> i32 {
    (sample as i32 - 2048) << 19
}

// ---------------------------------------------------------------------------
// Public pipeline entry points — called from the DSP Embassy task
// ---------------------------------------------------------------------------

/// Process the first half of the ADC ping-pong buffer (samples 0..FRAME_SAMPLES).
/// Writes results to the first half of the HRTIM ping-pong buffer.
///
/// # Safety
/// Must be called only from the context that owns the first buffer half
/// (i.e. after the DMA half-transfer flag has been set).
pub unsafe fn process_first_half() {
    let adc = adc_buf_first_half();
    let hrtim_out = hrtim_buf_first_half_mut();
    process_half(adc, hrtim_out);
}

/// Process the second half of the ADC ping-pong buffer (samples FRAME_SAMPLES..2×FRAME_SAMPLES).
/// Writes results to the second half of the HRTIM ping-pong buffer.
///
/// # Safety
/// Must be called only after the DMA transfer-complete flag has been set.
pub unsafe fn process_second_half() {
    let adc = adc_buf_second_half();
    let hrtim_out = hrtim_buf_second_half_mut();
    process_half(adc, hrtim_out);
}

// ---------------------------------------------------------------------------
// Internal pipeline implementation
// ---------------------------------------------------------------------------

/// Core pipeline: process one half-buffer of ADC samples into PwmSamples.
///
/// `adc_in`   : FRAME_SAMPLES raw ADC u16 samples (200 kHz)
/// `hrtim_out`: FRAME_SAMPLES PwmSample destination (200 kHz)
fn process_half(adc_in: &[u16], hrtim_out: &mut [PwmSample]) {
    debug_assert_eq!(adc_in.len(),   FRAME_SAMPLES);
    debug_assert_eq!(hrtim_out.len(), FRAME_SAMPLES);

    // --- Stage 1: convert ADC u16 → Q31 ---
    let mut q31_in = [0i32; FRAME_SAMPLES];
    for (dst, &src) in q31_in.iter_mut().zip(adc_in.iter()) {
        *dst = adc_to_q31(src);
    }

    // --- Stage 2: 10:1 FIR decimation → 10 Q31 samples at 20 kHz ---
    // Safety: DECIMATOR is only accessed from this function, which is called
    // from the single DSP task.
    let q31_in_arr: &[i32; FRAME_SAMPLES] =
        (&q31_in as &[i32]).try_into().unwrap();
    let _decimated: [i32; DECIMATED_LEN] =
        unsafe { DECIMATOR.process(q31_in_arr) };

    // --- Stage 3: audio IIR + compression --- TODO ---

    // --- Stage 4: Hilbert transform / SSB modulation --- TODO ---

    // --- Stage 5: 10:1 FIR interpolation + outphasing --- TODO ---

    // Placeholder: fill HRTIM buffer with silence (50 % duty on Timer A,
    // near-zero duty on Timer C) until the full pipeline is wired up.
    use crate::config::PWM_PERIOD;
    let silence = PwmSample {
        tim_a_cmp1: (PWM_PERIOD / 4) as u32,
        tim_a_cmp2: (PWM_PERIOD * 3 / 4) as u32,
        tim_b_cmp1: (PWM_PERIOD / 4) as u32,
        tim_b_cmp2: (PWM_PERIOD * 3 / 4) as u32,
        tim_c_cmp1: 1,
    };
    for slot in hrtim_out.iter_mut() {
        *slot = silence;
    }
}
