// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2025-2026 Christian Riesch, christian@riesch.at
//
// dsp.rs — Digital signal processing pipeline.
//
// Called from the DSP Embassy task whenever the DMA half/full-transfer ISR
// sets PROCESS_FIRST_HALF or PROCESS_SECOND_HALF.
//
// Pipeline per half-buffer (FRAME_SAMPLES = 100 ADC samples at 200 kHz):
//
//   adc_to_q31()         100 × u16  →  100 × i32 (Q31, DC-centred)
//   arm_fir_decimate_fast 100 × i32  →   10 × i32 (Q31, 20 kHz) [CMSIS-DSP]
//   q31_to_f32()          10 × i32  →   10 × f32
//   arm_biquad HP         10 × f32  →   10 × f32 (Chebyshev I HP, 200 Hz) [CMSIS-DSP]
//   compress()            10 × f32  →   10 × f32 (envelope follower, 4:1 ratio)
//   arm_biquad LP         10 × f32  →   10 × f32 (Chebyshev I LP, 2800 Hz) [CMSIS-DSP]
//   arm_fir_ssb_f32()     10 × f32  →  (10 × f32 I, 10 × f32 Q) analytic signal [C]
//   f32_to_q31()         (10 × I, 10 × Q) f32  →  (10 × I, 10 × Q) Q31
//   arm_fir_interpolate  (10 × Q31 I, 10 × Q31 Q)  →  (100 × Q31 I, 100 × Q31 Q) [CMSIS-DSP]
//   cordic + outphasing  (100 × I, 100 × Q) Q31  →  100 × PwmSample
//   write HRTIM ping-pong buffer half

use embassy_stm32::pac;

use crate::config::{FRAME_SAMPLES, PWM_PERIOD, TIMERC_PERIOD};
use crate::dsp_ffi::{
    ArmBiquadCascadeDf2TInstanceF32, ArmFirDecimateInstanceQ31,
    ArmFirInstanceF32, ArmFirInterpolateInstanceQ31,
    BIQUAD_HP_STATE_LEN, BIQUAD_LP_STATE_LEN,
    FIR_DEC_STATE_LEN, FIR_INTERP_STATE_LEN, SSB_STATE_LEN,
    arm_biquad_cascade_df2T_f32, arm_biquad_cascade_df2T_init_f32,
    arm_fir_decimate_init_q31, arm_fir_decimate_fast_q31,
    arm_fir_interpolate_init_q31, arm_fir_interpolate_q31,
    arm_fir_ssb_f32,
};
use crate::hrtim::{
    adc_buf_first_half, adc_buf_second_half,
    hrtim_buf_first_half_mut, hrtim_buf_second_half_mut,
    PwmSample,
};

// ---------------------------------------------------------------------------
// Pipeline constants
// ---------------------------------------------------------------------------

/// Decimation / interpolation factor.
pub const FIR_DECIMATE_FACTOR: usize = 10;

/// Number of taps in the prototype lowpass FIR.
pub const FIR_NUM_TAPS: usize = 60;

/// Output samples per half-buffer after 10:1 decimation (DSP rate = 20 kHz).
pub const DECIMATED_LEN: usize = FRAME_SAMPLES / FIR_DECIMATE_FACTOR; // 10

// ---------------------------------------------------------------------------
// FIR prototype lowpass coefficients (Q31, 60-tap Hamming, cutoff 5 kHz)
// Generated by tools/design_decimate_filter.ipynb — do not edit manually.
// ---------------------------------------------------------------------------
#[rustfmt::skip]
pub const FIR_COEFFS_Q31: [i32; FIR_NUM_TAPS] = [
      -1890794, -1971130, -2123936, -2324026, -2525779, -2663835,
      -2655228, -2402891, -1800394,  -737704,   892341,  3187185,
       6227709, 10071807, 14748755, 20254744, 26549872, 33556841,
      41161496, 49215254, 57539380, 65930935, 74170157, 82028943,
      89280014, 95706338,101110327,105322362,108208197,109674881,
     109674881,108208197,105322362,101110327, 95706338, 89280014,
      82028943, 74170157, 65930935, 57539380, 49215254, 41161496,
      33556841, 26549872, 20254744, 14748755, 10071807,  6227709,
       3187185,   892341,  -737704, -1800394, -2402891, -2655228,
      -2663835, -2525779, -2324026, -2123936, -1971130, -1890794,
];

// ---------------------------------------------------------------------------
// Audio IIR filter coefficients
// Generated by tools/design_audio_filters.ipynb — do not edit manually.
// ---------------------------------------------------------------------------

pub const HIGHPASS_STAGES: usize = 2;

/// Highpass: Chebyshev I order 4, 0.3 dB ripple, cutoff 200 Hz, fs = 20 kHz.
/// Coefficients per section: [b0, b1, b2, -a1, -a2] (DF2T, negated feedback).
#[rustfmt::skip]
pub const HIGHPASS_COEFFS: [[f32; 5]; HIGHPASS_STAGES] = [
    [8.8843882084e-01, -1.7768776417e+00,  8.8843882084e-01,  1.8572715521e+00, -8.6588841677e-01],
    [1.0000000000e+00, -2.0000000000e+00,  1.0000000000e+00,  1.9743645191e+00, -9.7780704498e-01],
];

pub const LOWPASS_STAGES: usize = 2;

/// Lowpass: Chebyshev I order 4, 0.3 dB ripple, cutoff 2800 Hz, fs = 20 kHz.
/// Coefficients per section: [b0, b1, b2, -a1, -a2] (DF2T, negated feedback).
#[rustfmt::skip]
pub const LOWPASS_COEFFS: [[f32; 5]; LOWPASS_STAGES] = [
    [1.0223765858e-02,  2.0447531715e-02,  1.0223765858e-02,  1.1647846699e+00, -4.0787613392e-01],
    [1.0000000000e+00,  2.0000000000e+00,  1.0000000000e+00,  1.0389341116e+00, -7.3549830914e-01],
];

// ---------------------------------------------------------------------------
// SSB analytic FIR coefficients
// Generated by tools/design_ssb_filter.ipynb — do not edit manually.
// ---------------------------------------------------------------------------

pub const SSB_FILTER_TAPS: usize = 257;

/// Interleaved I/Q coefficients for arm_fir_ssb_f32.
/// Layout: [real[0], imag[0], real[1], imag[1], ..., real[127], imag[127], real[128]]
/// Passband 530–9470 Hz at 20 kHz, 257-tap Remez equiripple.
#[rustfmt::skip]
pub const SSB_COEFFS_INTERLEAVED: [f32; SSB_FILTER_TAPS] = [
    -1.0015372709e-06,  -3.3779708701e-06,  2.2930228170e-06,  -1.9478195554e-06,
    3.3461501516e-06,  -1.9168621748e-06,  5.2559112191e-06,  -1.2431479490e-06,
    7.7128152043e-06,  3.5058798176e-07,  1.0480947822e-05,  3.1770571240e-06,
    1.3278330698e-05,  7.5202710832e-06,  1.5694196918e-05,  1.3611955183e-05,
    1.7181313524e-05,  2.1579917302e-05,  1.7058382582e-05,  3.1393814425e-05,
    1.4531447960e-05,  4.2810101149e-05,  8.7336657089e-06,  5.5321052059e-05,
    -1.2160819551e-06,  6.8112261943e-05,  -1.6135949409e-05,  8.0034253187e-05,
    -3.6687335523e-05,  8.9595356258e-05,  -6.3266161305e-05,  9.4980954600e-05,
    -9.5884810435e-05,  9.4105933385e-05,  -1.3405329082e-04,  8.4704472101e-05,
    -1.7667168868e-04,  6.4458290581e-05,  -2.2194175108e-04,  3.1157334888e-05,
    -2.6730718673e-04,  -1.7107584426e-05,  -3.0943291495e-04,  -8.1721678725e-05,
    -3.4423696343e-04,  -1.6330594372e-04,  -3.6698704935e-04,  -2.6148100733e-04,
    -3.7246421562e-04,  -3.7464901106e-04,  -3.5518512595e-04,  -4.9979775213e-04,
    -3.0968984356e-04,  -6.3234107802e-04,  -2.3093081836e-04,  -7.6608348172e-04,
    -1.1463979172e-04,  -8.9319678955e-04,  4.2201892938e-05,  -1.0043596849e-03,
    2.4092476815e-04,  -1.0889746482e-03,  4.8072510981e-04,  -1.1355153983e-03,
    7.5826630928e-04,  -1.1319892947e-03,  1.0673451470e-03,  -1.0665055597e-03,
    1.3986598933e-03,  -9.2794105876e-04,  1.7397002084e-03,  -7.0667639375e-04,
    2.0747862291e-03,  -3.9537489647e-04,  2.3852747399e-03,  1.0225045116e-05,
    2.6499389205e-03,  5.1055062795e-04,  2.8455299325e-03,  1.1014989577e-03,
    2.9475032352e-03,  1.7738512252e-03,  2.9309017118e-03,  2.5128242560e-03,
    2.7713598683e-03,  3.2977983356e-03,  2.4461979046e-03,  4.1022370569e-03,
    1.9355559489e-03,  4.8938053660e-03,  1.2235176982e-03,  5.6346827187e-03,
    2.9917375650e-04,  6.2820408493e-03,  -8.4243499441e-04,  6.7886435427e-03,
    -2.1995522548e-03,  7.1034799330e-03,  -3.7631618325e-03,  7.1723107249e-03,
    -5.5167032406e-03,  6.9379662164e-03,  -7.4360873550e-03,  6.3401162624e-03,
    -9.4900242984e-03,  5.3141033277e-03,  -1.1640660465e-02,  3.7881801836e-03,
    -1.3844528235e-02,  1.6779416474e-03,  -1.6053767875e-02,  -1.1242580367e-03,
    -1.8217587844e-02,  -4.7694551758e-03,  -2.0283894613e-02,  -9.4918282703e-03,
    -2.2201064974e-02,  -1.5692636371e-02,  -2.3919727653e-02,  -2.4136526510e-02,
    -2.5394538417e-02,  -3.6484256387e-02,  -2.6585834101e-02,  -5.7102695107e-02,
    -2.7461096644e-02,  -1.0211124271e-01,  -2.7996178716e-02,  -3.1696969271e-01,
    4.7182378173e-01,  3.1696969271e-01,  -2.7996178716e-02,  1.0211124271e-01,
    -2.7461096644e-02,  5.7102695107e-02,  -2.6585834101e-02,  3.6484256387e-02,
    -2.5394538417e-02,  2.4136526510e-02,  -2.3919727653e-02,  1.5692636371e-02,
    -2.2201064974e-02,  9.4918282703e-03,  -2.0283894613e-02,  4.7694551758e-03,
    -1.8217587844e-02,  1.1242580367e-03,  -1.6053767875e-02,  -1.6779416474e-03,
    -1.3844528235e-02,  -3.7881801836e-03,  -1.1640660465e-02,  -5.3141033277e-03,
    -9.4900242984e-03,  -6.3401162624e-03,  -7.4360873550e-03,  -6.9379662164e-03,
    -5.5167032406e-03,  -7.1723107249e-03,  -3.7631618325e-03,  -7.1034799330e-03,
    -2.1995522548e-03,  -6.7886435427e-03,  -8.4243499441e-04,  -6.2820408493e-03,
    2.9917375650e-04,  -5.6346827187e-03,  1.2235176982e-03,  -4.8938053660e-03,
    1.9355559489e-03,  -4.1022370569e-03,  2.4461979046e-03,  -3.2977983356e-03,
    2.7713598683e-03,  -2.5128242560e-03,  2.9309017118e-03,  -1.7738512252e-03,
    2.9475032352e-03,  -1.1014989577e-03,  2.8455299325e-03,  -5.1055062795e-04,
    2.6499389205e-03,  -1.0225045116e-05,  2.3852747399e-03,  3.9537489647e-04,
    2.0747862291e-03,  7.0667639375e-04,  1.7397002084e-03,  9.2794105876e-04,
    1.3986598933e-03,  1.0665055597e-03,  1.0673451470e-03,  1.1319892947e-03,
    7.5826630928e-04,  1.1355153983e-03,  4.8072510981e-04,  1.0889746482e-03,
    2.4092476815e-04,  1.0043596849e-03,  4.2201892938e-05,  8.9319678955e-04,
    -1.1463979172e-04,  7.6608348172e-04,  -2.3093081836e-04,  6.3234107802e-04,
    -3.0968984356e-04,  4.9979775213e-04,  -3.5518512595e-04,  3.7464901106e-04,
    -3.7246421562e-04,  2.6148100733e-04,  -3.6698704935e-04,  1.6330594372e-04,
    -3.4423696343e-04,  8.1721678725e-05,  -3.0943291495e-04,  1.7107584426e-05,
    -2.6730718673e-04,  -3.1157334888e-05,  -2.2194175108e-04,  -6.4458290581e-05,
    -1.7667168868e-04,  -8.4704472101e-05,  -1.3405329082e-04,  -9.4105933385e-05,
    -9.5884810435e-05,  -9.4980954600e-05,  -6.3266161305e-05,  -8.9595356258e-05,
    -3.6687335523e-05,  -8.0034253187e-05,  -1.6135949409e-05,  -6.8112261943e-05,
    -1.2160819551e-06,  -5.5321052059e-05,  8.7336657089e-06,  -4.2810101149e-05,
    1.4531447960e-05,  -3.1393814425e-05,  1.7058382582e-05,  -2.1579917302e-05,
    1.7181313524e-05,  -1.3611955183e-05,  1.5694196918e-05,  -7.5202710832e-06,
    1.3278330698e-05,  -3.1770571240e-06,  1.0480947822e-05,  -3.5058798176e-07,
    7.7128152043e-06,  1.2431479490e-06,  5.2559112191e-06,  1.9168621748e-06,
    3.3461501516e-06,  1.9478195554e-06,  2.2930228170e-06,  3.3779708701e-06,
    -1.0015372709e-06,
];

// ---------------------------------------------------------------------------
// Compressor
// ---------------------------------------------------------------------------

const COMP_THRESHOLD:    f32 = 0.3;
const COMP_RATIO:        f32 = 4.0;
const COMP_MAKEUP_GAIN:  f32 = 1.5;
const COMP_ATTACK_COEFF: f32 = 0.22119922_f32;   // 1 − exp(−1 / (20000 × 0.0002))
const COMP_RELEASE_COEFF: f32 = 0.00049987503_f32; // 1 − exp(−1 / (20000 × 0.1))

pub struct Compressor {
    envelope: f32,
    gain:     f32,
}

impl Compressor {
    pub const fn new() -> Self {
        Self { envelope: 0.0, gain: 1.0 }
    }

    pub fn process(&mut self, input: &[f32], output: &mut [f32]) {
        for (out, &sample) in output.iter_mut().zip(input.iter()) {
            let abs_s = if sample < 0.0 { -sample } else { sample };
            if abs_s > self.envelope {
                self.envelope += COMP_ATTACK_COEFF  * (abs_s - self.envelope);
            } else {
                self.envelope += COMP_RELEASE_COEFF * (abs_s - self.envelope);
            }
            if self.envelope > COMP_THRESHOLD {
                let overshoot  = self.envelope / COMP_THRESHOLD;
                let compressed = 1.0 + (overshoot - 1.0) / COMP_RATIO;
                self.gain      = COMP_THRESHOLD * compressed / self.envelope;
            } else {
                self.gain = 1.0;
            }
            let s = sample * self.gain * COMP_MAKEUP_GAIN;
            *out = if s > 1.0 { 1.0 } else if s < -1.0 { -1.0 } else { s };
        }
    }
}

// ---------------------------------------------------------------------------
// Sample format conversion helpers
// ---------------------------------------------------------------------------

/// Convert a 12-bit right-aligned ADC sample (0…4095) to Q31.
#[inline]
pub fn adc_to_q31(sample: u16) -> i32 {
    (sample as i32 - 2048) << 19
}

/// Convert a Q31 sample to normalised f32 in [−1.0, 1.0).
#[inline]
pub fn q31_to_f32(sample: i32) -> f32 {
    sample as f32 * (1.0 / 2_147_483_648.0_f32)
}

/// Convert a normalised f32 in [−1.0, 1.0] to Q31, saturating at limits.
#[inline]
pub fn f32_to_q31(sample: f32) -> i32 {
    let v = sample * 2_147_483_648.0_f32;
    if v >= i32::MAX as f32 { i32::MAX }
    else if v <= i32::MIN as f32 { i32::MIN }
    else { v as i32 }
}

// ---------------------------------------------------------------------------
// CORDIC outphasing constants
// ---------------------------------------------------------------------------

/// Transmission amplitude — sets the PA supply voltage via the buck converter.
/// Expressed in Timer C ticks (TIMERC_PERIOD = 850).  Higher = more TX power.
const AMPLITUDE: u32 = TIMERC_PERIOD / 2; // = 425 ticks

// ---------------------------------------------------------------------------
// CMSIS-DSP filter state buffers
// ---------------------------------------------------------------------------

static mut FIR_DEC_STATE:      [i32; FIR_DEC_STATE_LEN]    = [0; FIR_DEC_STATE_LEN];
static mut FIR_INTERP_I_STATE: [i32; FIR_INTERP_STATE_LEN] = [0; FIR_INTERP_STATE_LEN];
static mut FIR_INTERP_Q_STATE: [i32; FIR_INTERP_STATE_LEN] = [0; FIR_INTERP_STATE_LEN];
static mut BIQUAD_HP_STATE:    [f32; BIQUAD_HP_STATE_LEN]   = [0.0; BIQUAD_HP_STATE_LEN];
static mut BIQUAD_LP_STATE:    [f32; BIQUAD_LP_STATE_LEN]   = [0.0; BIQUAD_LP_STATE_LEN];

// ---------------------------------------------------------------------------
// CMSIS-DSP filter instances (null-initialised; filled by init())
// ---------------------------------------------------------------------------

static mut FIR_DEC_INST: ArmFirDecimateInstanceQ31 = ArmFirDecimateInstanceQ31 {
    m: 0, num_taps: 0, p_coeffs: core::ptr::null(), p_state: core::ptr::null_mut(),
};
static mut FIR_INTERP_I_INST: ArmFirInterpolateInstanceQ31 = ArmFirInterpolateInstanceQ31 {
    l: 0, phase_length: 0, p_coeffs: core::ptr::null(), p_state: core::ptr::null_mut(),
};
static mut FIR_INTERP_Q_INST: ArmFirInterpolateInstanceQ31 = ArmFirInterpolateInstanceQ31 {
    l: 0, phase_length: 0, p_coeffs: core::ptr::null(), p_state: core::ptr::null_mut(),
};
static mut BIQUAD_HP_INST: ArmBiquadCascadeDf2TInstanceF32 = ArmBiquadCascadeDf2TInstanceF32 {
    num_stages: 0, p_state: core::ptr::null_mut(), p_coeffs: core::ptr::null(),
};
static mut BIQUAD_LP_INST: ArmBiquadCascadeDf2TInstanceF32 = ArmBiquadCascadeDf2TInstanceF32 {
    num_stages: 0, p_state: core::ptr::null_mut(), p_coeffs: core::ptr::null(),
};

// ---------------------------------------------------------------------------
// SSB FIR filter instance and state buffer
// ---------------------------------------------------------------------------

static mut SSB_STATE: [f32; SSB_STATE_LEN] = [0.0; SSB_STATE_LEN];

static mut SSB_INST: ArmFirInstanceF32 = ArmFirInstanceF32 {
    num_taps: 0, p_state: core::ptr::null_mut(), p_coeffs: core::ptr::null(),
};

// ---------------------------------------------------------------------------
// Compressor (pure Rust)
// ---------------------------------------------------------------------------

static mut COMPRESSOR: Compressor = Compressor::new();

// ---------------------------------------------------------------------------
// CORDIC initialisation and per-sample calculation
// ---------------------------------------------------------------------------

/// Initialise the CORDIC peripheral and all CMSIS-DSP filter instances.
///
/// Must be called once during hardware init, before any process_*_half call.
pub fn init() {
    // --- CORDIC: MODULUS function, Q1.31, 60 iterations ---
    pac::RCC.ahb1enr().modify(|w| w.set_cordicen(true));
    pac::RCC.ahb1rstr().modify(|w| w.set_cordicrst(true));
    pac::RCC.ahb1rstr().modify(|w| w.set_cordicrst(false));

    pac::CORDIC.csr().write(|w| {
        w.set_func(pac::cordic::vals::Func::from_bits(3));           // MODULUS
        w.set_precision(pac::cordic::vals::Precision::from_bits(15));// 60 iterations
        w.set_scale(pac::cordic::vals::Scale::from_bits(0));
        w.set_nargs(pac::cordic::vals::Num::NUM2);
        w.set_nres(pac::cordic::vals::Num::NUM2);
        w.set_argsize(pac::cordic::vals::Size::BITS32);
        w.set_ressize(pac::cordic::vals::Size::BITS32);
    });

    // --- CMSIS-DSP filter initialisation ---
    unsafe {
        // FIR decimator: 60-tap lowpass, factor 10, input block = 100 samples.
        arm_fir_decimate_init_q31(
            &raw mut FIR_DEC_INST,
            FIR_NUM_TAPS as u16,
            FIR_DECIMATE_FACTOR as u8,
            FIR_COEFFS_Q31.as_ptr(),
            core::ptr::addr_of_mut!(FIR_DEC_STATE[0]),
            FRAME_SAMPLES as u32,
        );

        // Biquad highpass (2-stage Chebyshev I, 200 Hz, fs = 20 kHz).
        // HIGHPASS_COEFFS is [[f32;5];2]; memory layout is the same as [f32;10].
        arm_biquad_cascade_df2T_init_f32(
            &raw mut BIQUAD_HP_INST,
            HIGHPASS_STAGES as u8,
            HIGHPASS_COEFFS[0].as_ptr(),
            core::ptr::addr_of_mut!(BIQUAD_HP_STATE[0]),
        );

        // Biquad lowpass (2-stage Chebyshev I, 2800 Hz, fs = 20 kHz).
        arm_biquad_cascade_df2T_init_f32(
            &raw mut BIQUAD_LP_INST,
            LOWPASS_STAGES as u8,
            LOWPASS_COEFFS[0].as_ptr(),
            core::ptr::addr_of_mut!(BIQUAD_LP_STATE[0]),
        );

        // FIR interpolators (I and Q paths): factor 10, input block = 10 samples.
        arm_fir_interpolate_init_q31(
            &raw mut FIR_INTERP_I_INST,
            FIR_DECIMATE_FACTOR as u8,
            FIR_NUM_TAPS as u16,
            FIR_COEFFS_Q31.as_ptr(),
            core::ptr::addr_of_mut!(FIR_INTERP_I_STATE[0]),
            DECIMATED_LEN as u32,
        );
        arm_fir_interpolate_init_q31(
            &raw mut FIR_INTERP_Q_INST,
            FIR_DECIMATE_FACTOR as u8,
            FIR_NUM_TAPS as u16,
            FIR_COEFFS_Q31.as_ptr(),
            core::ptr::addr_of_mut!(FIR_INTERP_Q_STATE[0]),
            DECIMATED_LEN as u32,
        );

        // SSB analytic FIR (arm_fir_ssb_f32): 257 taps, interleaved I/Q coefficients.
        SSB_INST.num_taps = SSB_FILTER_TAPS as u16;
        SSB_INST.p_coeffs = SSB_COEFFS_INTERLEAVED.as_ptr();
        SSB_INST.p_state  = core::ptr::addr_of_mut!(SSB_STATE[0]);
    }
}

/// Zero-overhead pipelined CORDIC MODULUS for a vector of (I, Q) pairs.
///
/// Implements the RM0440 §17.3.6 zero-overhead pipeline:
///   • Write I[0],Q[0]           → launches calc[0]
///   • Write I[1],Q[1]           → queues  calc[1]
///   • Loop: read mod[i]+phase[i] → triggers calc[i+1]; write I[i+2],Q[i+2]
///   • Drain last two results
///
/// Reading CORDIC_RDATA inserts bus wait-states until the result is ready, so
/// there is no polling loop and no idle cycles between successive calculations.
///
/// CORDIC_CSR must already be configured for MODULUS, NARGS=1, NRES=1 (Q1.31).
pub unsafe fn cordic_modulus_vec(
    i_vals:    &[i32],
    q_vals:    &[i32],
    mod_out:   &mut [i32],
    phase_out: &mut [i32],
) {
    let n = i_vals.len();
    debug_assert!(n >= 1);

    let c = pac::CORDIC;

    if n == 1 {
        c.wdata().write_value(i_vals[0] as u32);
        c.wdata().write_value(q_vals[0] as u32);
        mod_out[0]   = c.rdata().read() as i32;
        phase_out[0] = c.rdata().read() as i32;
        return;
    }

    // Prime: launch calc[0], queue calc[1].
    c.wdata().write_value(i_vals[0] as u32);
    c.wdata().write_value(q_vals[0] as u32); // launches calc[0]
    c.wdata().write_value(i_vals[1] as u32);
    c.wdata().write_value(q_vals[1] as u32); // queues  calc[1]

    // Pipelined drain: read calc[i], queue calc[i+2].
    for i in 0..n - 2 {
        mod_out[i]   = c.rdata().read() as i32; // stalls until calc[i] done
        phase_out[i] = c.rdata().read() as i32; // triggers calc[i+1]
        c.wdata().write_value(i_vals[i + 2] as u32);
        c.wdata().write_value(q_vals[i + 2] as u32); // queues calc[i+2]
    }

    // Drain calc[n-2] (running; calc[n-1] already queued by last loop iteration).
    mod_out[n - 2]   = c.rdata().read() as i32;
    phase_out[n - 2] = c.rdata().read() as i32; // triggers calc[n-1]

    // Drain calc[n-1].
    mod_out[n - 1]   = c.rdata().read() as i32;
    phase_out[n - 1] = c.rdata().read() as i32;
}

// ---------------------------------------------------------------------------
// Per-stage timing — always collected; ~11 volatile reads overhead (~11 cy).
// Fields are DWT CYCCNT deltas; meaningful only when DWT is enabled.
// ---------------------------------------------------------------------------

/// Per-stage cycle counts returned by every `process_first/second_half()` call.
/// All fields are DWT CYCCNT deltas.  Enable DWT (TRCENA + CYCCNTENA) to get
/// real numbers; if DWT is off all fields are zero.  The DSP task drops the
/// return value so the compiler eliminates the dead arithmetic at -Ofast.
pub struct PipelineTimings {
    pub stage1_adc_to_q31:   u32,  // u16 → Q31 conversion (100 samples)
    pub stage2_fir_decimate:  u32,  // 10:1 FIR decimation (CMSIS-DSP Q31)
    pub stage3a_q31_to_f32:  u32,  // Q31 → f32 conversion (10 samples)
    pub stage3b_highpass:    u32,  // Chebyshev I HP biquad (CMSIS-DSP f32)
    pub stage3c_compress:    u32,  // Envelope-follower compressor (Rust)
    pub stage3d_lowpass:     u32,  // Chebyshev I LP biquad (CMSIS-DSP f32)
    pub stage4_ssb:          u32,  // 257-tap analytic FIR I+Q (C arm_fir_ssb_f32)
    pub stage5a_f32_to_q31:  u32,  // f32 → Q31 conversion (I and Q, 10 samples each)
    pub stage5b_interpolate:  u32,  // 10:1 FIR interpolation I+Q (CMSIS-DSP Q31)
    pub stage5c_cordic:       u32,  // CORDIC MODULUS vector (zero-overhead, 100 samples)
    pub stage5c_outphasing:   u32,  // outphasing: mod/phase → PwmSample (100 samples)
    pub total:                u32,  // wall-clock total (includes all overhead)
}

/// Read DWT CYCCNT directly.
#[inline(always)]
fn cyccnt() -> u32 {
    unsafe { (0xE000_1004 as *const u32).read_volatile() }
}

// ---------------------------------------------------------------------------
// Public pipeline entry points — called from the DSP Embassy task
// ---------------------------------------------------------------------------

/// Process the first half of the ADC ping-pong buffer (samples 0..FRAME_SAMPLES).
///
/// Returns per-stage DWT cycle counts; the DSP task drops them.  Enable DWT
/// before calling if the timing data is needed (see test_dsp_timing).
///
/// # Safety
/// Must be called only from the context that owns the first buffer half.
pub unsafe fn process_first_half() -> PipelineTimings {
    let adc = adc_buf_first_half();
    let hrtim_out = hrtim_buf_first_half_mut();
    process_half(adc, hrtim_out)
}

/// Process the second half of the ADC ping-pong buffer.
///
/// # Safety
/// Must be called only after the DMA transfer-complete flag has been set.
pub unsafe fn process_second_half() -> PipelineTimings {
    let adc = adc_buf_second_half();
    let hrtim_out = hrtim_buf_second_half_mut();
    process_half(adc, hrtim_out)
}

// ---------------------------------------------------------------------------
// Internal pipeline implementation
// ---------------------------------------------------------------------------

#[allow(static_mut_refs)]
unsafe fn process_half(adc_in: &[u16], hrtim_out: &mut [PwmSample]) -> PipelineTimings {
    debug_assert_eq!(adc_in.len(),    FRAME_SAMPLES);
    debug_assert_eq!(hrtim_out.len(), FRAME_SAMPLES);

    // --- Stage 1: ADC u16 → Q31 (DC centred) ---
    let t_start = cyccnt();
    let mut q31_in = [0i32; FRAME_SAMPLES];
    for (dst, &src) in q31_in.iter_mut().zip(adc_in.iter()) {
        *dst = adc_to_q31(src);
    }
    let t1 = cyccnt();

    // --- Stage 2: 10:1 FIR decimation → 10 Q31 samples at 20 kHz ---
    let mut decimated = [0i32; DECIMATED_LEN];
    arm_fir_decimate_fast_q31(
        &FIR_DEC_INST,
        q31_in.as_ptr(),
        decimated.as_mut_ptr(),
        FRAME_SAMPLES as u32,
    );
    let t2 = cyccnt();

    // --- Stage 3a: Q31 → f32 ---
    let mut audio = [0.0f32; DECIMATED_LEN];
    for (dst, &src) in audio.iter_mut().zip(decimated.iter()) {
        *dst = q31_to_f32(src);
    }
    let t3a = cyccnt();

    // --- Stage 3b: highpass IIR (Chebyshev I, 200 Hz) ---
    let mut hp_out = [0.0f32; DECIMATED_LEN];
    arm_biquad_cascade_df2T_f32(
        &BIQUAD_HP_INST,
        audio.as_ptr(),
        hp_out.as_mut_ptr(),
        DECIMATED_LEN as u32,
    );
    let t3b = cyccnt();

    // --- Stage 3c: compression ---
    let mut compressed = [0.0f32; DECIMATED_LEN];
    COMPRESSOR.process(&hp_out, &mut compressed);
    let t3c = cyccnt();

    // --- Stage 3d: lowpass IIR (Chebyshev I, 2800 Hz) ---
    let mut lp_out = [0.0f32; DECIMATED_LEN];
    arm_biquad_cascade_df2T_f32(
        &BIQUAD_LP_INST,
        compressed.as_ptr(),
        lp_out.as_mut_ptr(),
        DECIMATED_LEN as u32,
    );
    let t3d = cyccnt();

    // --- Stage 4: SSB analytic FIR → I and Q paths ---
    let mut ssb_i = [0.0f32; DECIMATED_LEN];
    let mut ssb_q = [0.0f32; DECIMATED_LEN];
    arm_fir_ssb_f32(
        &SSB_INST,
        lp_out.as_ptr(),
        ssb_i.as_mut_ptr(),
        ssb_q.as_mut_ptr(),
        DECIMATED_LEN as u32,
    );
    let t4 = cyccnt();

    // --- Stage 5a: f32 → Q31 ---
    let mut q31_i = [0i32; DECIMATED_LEN];
    let mut q31_q = [0i32; DECIMATED_LEN];
    for (dst, &src) in q31_i.iter_mut().zip(ssb_i.iter()) {
        *dst = f32_to_q31(src);
    }
    for (dst, &src) in q31_q.iter_mut().zip(ssb_q.iter()) {
        *dst = f32_to_q31(src);
    }
    let t5a = cyccnt();

    // --- Stage 5b: 10:1 FIR interpolation → 100 Q31 samples at 200 kHz ---
    let mut interp_i = [0i32; FRAME_SAMPLES];
    let mut interp_q = [0i32; FRAME_SAMPLES];
    arm_fir_interpolate_q31(
        &FIR_INTERP_I_INST,
        q31_i.as_ptr(),
        interp_i.as_mut_ptr(),
        DECIMATED_LEN as u32,
    );
    arm_fir_interpolate_q31(
        &FIR_INTERP_Q_INST,
        q31_q.as_ptr(),
        interp_q.as_mut_ptr(),
        DECIMATED_LEN as u32,
    );
    let t5b = cyccnt();

    // --- Stage 5c: CORDIC polar conversion + outphasing → HRTIM compare values ---
    let mut cordic_mod   = [0i32; FRAME_SAMPLES];
    let mut cordic_phase = [0i32; FRAME_SAMPLES];
    cordic_modulus_vec(&interp_i, &interp_q, &mut cordic_mod, &mut cordic_phase);
    let t5c = cyccnt();

    // All intermediate values stay within i32 (PWM_PERIOD=744, AMPLITUDE=425),
    // so i64 is not needed.  Modulo by a non-power-of-2 constant is replaced
    // with a single conditional subtract, which is cheaper than the compiler's
    // reciprocal-multiply trick.
    let half = PWM_PERIOD as i32 / 2; // 372
    for (i, slot) in hrtim_out.iter_mut().enumerate() {
        let modulus = cordic_mod[i];
        let phase   = cordic_phase[i];

        // CORDIC MODULUS output is non-negative Q1.31; scale to amplitude ticks.
        // Compensate for the 1/L gain of the CMSIS polyphase interpolator.
        let mag = ((modulus >> 15) * (AMPLITUDE as i32 * FIR_DECIMATE_FACTOR as i32)) >> 16;
        let tc_cmp1 = (mag as u32).clamp(3, AMPLITUDE);

        // Shift before negating to avoid i32::MIN overflow on negation.
        // phase_ticks ∈ [0, PWM_PERIOD]; conditional subtract instead of %.
        let phase_ticks = (-(phase >> 15) * half >> 16) + half;
        let ta_cmp1 = if phase_ticks >= PWM_PERIOD as i32 {
            (phase_ticks - PWM_PERIOD as i32) as u32
        } else {
            phase_ticks as u32
        };
        // ta_cmp1 + half ∈ [372, 1115], so one conditional subtract suffices.
        let t = ta_cmp1 + PWM_PERIOD / 2;
        let ta_cmp2 = if t >= PWM_PERIOD { t - PWM_PERIOD } else { t };

        *slot = PwmSample {
            tim_a_cmp1: ta_cmp1,
            tim_a_cmp2: ta_cmp2,
            tim_b_cmp1: ta_cmp1,
            tim_b_cmp2: ta_cmp2,
            tim_c_cmp1: tc_cmp1,
        };
    }
    let t_end = cyccnt();

    PipelineTimings {
        stage1_adc_to_q31:   t1.wrapping_sub(t_start),
        stage2_fir_decimate:  t2.wrapping_sub(t1),
        stage3a_q31_to_f32:  t3a.wrapping_sub(t2),
        stage3b_highpass:    t3b.wrapping_sub(t3a),
        stage3c_compress:    t3c.wrapping_sub(t3b),
        stage3d_lowpass:     t3d.wrapping_sub(t3c),
        stage4_ssb:          t4.wrapping_sub(t3d),
        stage5a_f32_to_q31:  t5a.wrapping_sub(t4),
        stage5b_interpolate: t5b.wrapping_sub(t5a),
        stage5c_cordic:      t5c.wrapping_sub(t5b),
        stage5c_outphasing:  t_end.wrapping_sub(t5c),
        total:               t_end.wrapping_sub(t_start),
    }
}
